name = "charity-app"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-20"

# PRODUCTION ENVIRONMENT
[[d1_databases]]
binding = "DB"
database_name = "charity-db"
database_id = "210266c7-283d-4410-b4b3-33ad43d2131e"

# STAGING ENVIRONMENT (Phase 1)
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "charity-db-staging"
database_id = "e24e3e4a-9cd4-46b2-ad5a-bedbf360c346"
