import React, { useCallback, useEffect, useState } from 'react';
import { AlertCircle, BarChart3, FileText, Folder, TrendingUp, Users } from 'lucide-react';
import { CloudDonorProfileModal } from '../components/CloudDonorProfileModal';

type Tab='monthly'|'open_pledges'|'by_fundraiser'|'by_category'|'by_donor'|'by_project'|'tax_summary';
const money=(value:any)=>Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const tabs:[Tab,string,React.ElementType][]=[['monthly','Monthly Income',TrendingUp],['open_pledges','Open Pledges',AlertCircle],['by_fundraiser','By Fundraiser',Users],['by_category','By Category',BarChart3],['by_donor','Donor History',FileText],['by_project','Project Costs',Folder],['tax_summary','Tax Summary',FileText]];

export const OnlineReports:React.FC=()=>{const[tab,setTab]=useState<Tab>('monthly');const[items,setItems]=useState<any[]>([]);const[page,setPage]=useState(1);const[totalPages,setTotalPages]=useState(1);const[grandTotal,setGrandTotal]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[donorId,setDonorId]=useState<string|null>(null);
const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const response=await fetch(`/api/v3/reports?tab=${tab}&page=${page}&limit=50`);const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to load report.');setItems(data.items||[]);setTotalPages(Math.max(1,data.totalPages||1));setGrandTotal(Number(data.grandTotal||0));setError('');}catch(reason:any){if(!silent)setError(reason.message||'Unable to load report.');}finally{if(!silent)setLoading(false);}},[tab,page]);useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),5000);return()=>window.clearInterval(timer);},[load]);const switchTab=(value:Tab)=>{setTab(value);setPage(1);};const max=Math.max(1,...items.map(item=>Number(item.total||item.balance||0)));
return <div><div style={{display:'flex',gap:8,marginBottom:28,flexWrap:'wrap'}}>{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>switchTab(key)} style={{display:'flex',alignItems:'center',gap:8,padding:'10px 18px',borderRadius:999,cursor:'pointer',fontFamily:'inherit',fontWeight:700,fontSize:'.9rem',background:tab===key?'linear-gradient(135deg,var(--navy-light),var(--navy))':'var(--bg-card)',color:tab===key?'#fff':'var(--text-secondary)',boxShadow:tab===key?'0 4px 16px rgba(37,99,235,.3)':'var(--shadow-sm)',border:tab===key?'2px solid transparent':'1px solid var(--border)'}}><Icon size={16}/>{label}</button>)}</div>{error&&<div className="card" style={{color:'var(--red)',marginBottom:16}}>{error}</div>}<div className="card">{loading?<div style={{padding:40,textAlign:'center'}}>Loading report...</div>:<ReportBody tab={tab} items={items} max={max} grandTotal={grandTotal} onDonor={setDonorId}/>} {totalPages>1&&<div style={{display:'flex',justifyContent:'space-between',marginTop:20,paddingTop:16,borderTop:'1px solid var(--border)'}}><span>Page {page} of {totalPages} · 50 rows maximum</span><div style={{display:'flex',gap:8}}><button className="btn btn-secondary btn-sm" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><button className="btn btn-secondary btn-sm" disabled={page>=totalPages} onClick={()=>setPage(value=>value+1)}>Next</button></div></div>}</div>{donorId&&<CloudDonorProfileModal donorId={donorId} onClose={()=>setDonorId(null)} onEdit={()=>undefined}/>}</div>};

const ReportBody:React.FC<{tab:Tab;items:any[];max:number;grandTotal:number;onDonor:(id:string)=>void}>=({tab,items,max,grandTotal,onDonor})=>{if(tab==='monthly'||tab==='by_category')return <><h2 style={{margin:'0 0 4px',color:'var(--navy)'}}>{tab==='monthly'?'Monthly Actual Income':'Income by Donation Category'}</h2><p style={{margin:'0 0 24px',color:'var(--text-muted)'}}>Approved payments only — calculated directly from the online ledger</p><div style={{display:'flex',flexDirection:'column',gap:12}}>{items.map(item=><div key={item.label||item.name} style={{display:'grid',gridTemplateColumns:'160px 1fr 120px',gap:16,alignItems:'center'}}><strong>{item.label||item.name}</strong><div style={{background:'var(--bg-input)',borderRadius:999,height:11,overflow:'hidden'}}><div style={{width:`${Number(item.total||0)/max*100}%`,height:'100%',background:tab==='monthly'?'linear-gradient(90deg,var(--navy-light),var(--navy))':'linear-gradient(90deg,var(--gold-light),var(--gold))'}}/></div><strong style={{textAlign:'right',color:'var(--navy)'}}>${money(item.total)}</strong></div>)}</div><Total value={grandTotal}/></>;
if(tab==='open_pledges')return <><h2 style={{margin:'0 0 4px',color:'var(--navy)'}}>Open Pledges — Action Required</h2><p style={{margin:'0 0 20px',color:'var(--text-muted)'}}>Balances not covered by approved, pending, or active scheduled payments</p><Table headers={['Donor','Phone','Open Balance','Action']} rows={items.map(item=><tr key={item.id} onClick={()=>onDonor(item.id)} style={{cursor:'pointer'}}><td><strong>{item.name}</strong></td><td>{item.phone||'—'}</td><td style={{fontWeight:800,color:'var(--red)'}}>${money(item.balance)}</td><td><span className="badge" style={{background:'var(--red-bg)',color:'var(--red)'}}>Follow Up</span></td></tr>)}/><Total value={grandTotal}/></>;
if(tab==='by_fundraiser')return <><h2 style={{margin:'0 0 20px',color:'var(--navy)'}}>Performance by Fundraiser</h2><Table headers={['Fundraiser','Commission %','Total Raised','Commission Earned']} rows={items.map(item=><tr key={item.id}><td><strong>{item.name}</strong><div style={{fontSize:12,color:'var(--text-muted)'}}>{item.email}</div></td><td>{item.percentage}%</td><td style={{color:'var(--green)',fontWeight:700}}>${money(item.total)}</td><td style={{fontWeight:700}}>${money(item.commission)}</td></tr>)}/></>;
if(tab==='by_donor')return <><h2 style={{margin:'0 0 20px',color:'var(--navy)'}}>Full Donor History</h2><Table headers={['Donor','Payments','First Gift','Last Gift','Total Given']} rows={items.map(item=><tr key={item.id} onClick={()=>onDonor(item.id)} style={{cursor:'pointer'}}><td><strong>{item.name}</strong></td><td>{item.count}</td><td>{item.first_date}</td><td>{item.last_date}</td><td style={{fontWeight:800,color:'var(--green)'}}>${money(item.total)}</td></tr>)}/><Total value={grandTotal}/></>;
if(tab==='by_project')return <><h2 style={{margin:'0 0 20px',color:'var(--navy)'}}>Project Income & Costs</h2><Table headers={['Project','Income','Costs','Net']} rows={items.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td style={{color:'var(--green)'}}>${money(item.income)}</td><td style={{color:'var(--red)'}}>${money(item.cost)}</td><td style={{fontWeight:800,color:Number(item.income)-Number(item.cost)>=0?'var(--green)':'var(--red)'}}>${money(Number(item.income)-Number(item.cost))}</td></tr>)}/></>;
return <><h2 style={{margin:'0 0 20px',color:'var(--navy)'}}>Tax Summary — Taxable Expenses</h2><Table headers={['Tax Year','Taxable Bills','Taxable Expense Total']} rows={items.map(item=><tr key={item.year}><td><strong>{item.year}</strong></td><td>{item.count}</td><td style={{fontWeight:800}}>${money(item.total)}</td></tr>)}/><Total value={grandTotal}/></>};
const Table:React.FC<{headers:string[];rows:React.ReactNode[]}>=({headers,rows})=><div className="table-container"><table><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={headers.length} style={{textAlign:'center',padding:30,color:'var(--text-muted)'}}>No records in this report.</td></tr>}</tbody></table></div>;
const Total:React.FC<{value:number}>=({value})=><div style={{marginTop:20,paddingTop:16,borderTop:'2px solid var(--border)',display:'flex',justifyContent:'space-between',fontWeight:800,color:'var(--navy)'}}><span>Grand Total</span><span>${money(value)}</span></div>;
