import React, { useCallback, useEffect, useRef, useState } from 'react';
import { CloudScheduleDetailsModal } from '../components/CloudScheduleDetailsModal';
import { SortableTh, type SortDirection } from '../components/SortableTh';

type Schedule = { id: string; revision: number; donorId: string; donorName: string; amount: number; currency: 'CAD' | 'USD'; frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'; nextDate: string; endDate?: string; paymentsRemaining?: number; totalPayments?: number; method: string; active: boolean };
type Donor = { id: string; name: string };
type ScheduleForm = { id: string; revision: number; donorId: string; amount: string; currency: 'CAD' | 'USD'; frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'; nextDate: string; endDate: string; method: string; active: boolean };
const blank = (): ScheduleForm => ({ id: '', revision: 0, donorId: '', amount: '', currency: 'CAD', frequency: 'monthly', nextDate: new Date().toISOString().slice(0, 10), endDate: '', method: 'credit_card', active: true });

export const OnlineSchedules: React.FC = () => {
  const [items, setItems] = useState<Schedule[]>([]);
  const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [total, setTotal] = useState(0);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [editing, setEditing] = useState(false); const [deletingAll, setDeletingAll] = useState(false);
  const [form, setForm] = useState(blank()); const [donorSearch, setDonorSearch] = useState(''); const [donors, setDonors] = useState<Donor[]>([]);
  const [selectedSchedule, setSelectedSchedule] = useState<Schedule | null>(null);
  const [sort, setSort] = useState('nextDate'); const [direction, setDirection] = useState<SortDirection>('asc');
  const changeSort = (column: string) => { setDirection(current => sort === column ? (current === 'asc' ? 'desc' : 'asc') : (column === 'amount' ? 'desc' : 'asc')); setSort(column); setPage(1); };
  const requestId = useRef('');
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); try { const response = await fetch(`/api/v3/schedules?page=${page}&limit=50&status=${status}&search=${encodeURIComponent(search)}&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&sort=${sort}&direction=${direction}`); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Unable to load schedules.'); setItems(data.items); setTotal(Number(data.total || 0)); setTotalPages(Math.max(1, Number(data.totalPages || 1))); } catch (e: any) { if (!silent) setError(e.message || 'Unable to load schedules.'); } finally { if (!silent) setLoading(false); } }, [page, search, status, from, to, sort, direction]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(true), 3000); return () => window.clearInterval(timer); }, [load]);
  useEffect(() => { const timer = window.setTimeout(() => { fetch(`/api/v3/donors?limit=50&search=${encodeURIComponent(donorSearch)}`).then(response => response.json()).then(data => { if (data.success) setDonors(data.items); }).catch(() => undefined); }, 250); return () => window.clearTimeout(timer); }, [donorSearch]);
  const beginNew = () => { setForm(blank()); setDonorSearch(''); setEditing(true); setError(''); setNotice(''); requestId.current = ''; };
  const beginEdit = (item: Schedule) => { setForm({ id: item.id, revision: item.revision, donorId: item.donorId, amount: String(item.amount), currency: item.currency, frequency: item.frequency, nextDate: item.nextDate, endDate: item.endDate || '', method: item.method, active: item.active }); setDonorSearch(item.donorName); setDonors(current => current.some(donor => donor.id === item.donorId) ? current : [{ id: item.donorId, name: item.donorName }, ...current]); setEditing(true); setError(''); setNotice(''); requestId.current = ''; };
  const write = async (item: Schedule | null, data: any) => { const key = crypto.randomUUID(); const id = item?.id || form.id; const response = await fetch(id ? `/api/v3/records/recurringPayments/${encodeURIComponent(id)}` : '/api/v3/records/recurringPayments', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify({ revision: item?.revision ?? form.revision, data }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || 'Unable to save schedule.'); return result; };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const amount = Number(form.amount); if (!form.donorId || !Number.isFinite(amount) || amount <= 0 || !form.nextDate) { setError('Donor, positive amount, and next date are required.'); return; } const key = requestId.current || crypto.randomUUID(); requestId.current = key; const data = { ...(form.id ? { id: form.id } : {}), donorId: form.donorId, amount, currency: form.currency, frequency: form.frequency, nextDate: form.nextDate, ...(form.endDate ? { endDate: form.endDate } : {}), method: form.method, active: form.active }; try { const response = await fetch(form.id ? `/api/v3/records/recurringPayments/${encodeURIComponent(form.id)}` : '/api/v3/records/recurringPayments', { method: form.id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify({ revision: form.revision, data }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || 'Unable to save schedule.'); requestId.current = ''; setEditing(false); setNotice('Schedule saved to the cloud.'); await load(true); } catch (e: any) { requestId.current = ''; setError(e.message || 'Unable to save schedule.'); } };
  const toggle = async (item: Schedule) => { try { await write(item, { active: !item.active }); setNotice(item.active ? 'Schedule paused.' : 'Schedule resumed.'); await load(true); } catch (e: any) { setError(e.message || 'Unable to update schedule.'); } };
  const remove = async (item: Schedule) => { if (!window.confirm(`Delete the recurring payment for ${item.donorName}?`)) return; try { const key = crypto.randomUUID(); const response = await fetch(`/api/v3/records/recurringPayments/${encodeURIComponent(item.id)}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify({ revision: item.revision }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || 'Unable to delete schedule.'); setNotice('Schedule deleted from the cloud.'); await load(true); } catch (e: any) { setError(e.message || 'Unable to delete schedule.'); } };
  const removeAll = async () => { if (!total || !window.confirm(`Delete all ${total.toLocaleString()} scheduled payments from CharityPro? This does not cancel schedules in Sola.`)) return; setDeletingAll(true); setError(''); try { const response = await fetch('/api/v3/schedules', { method: 'DELETE', headers: { 'Idempotency-Key': crypto.randomUUID() } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || 'Unable to delete all schedules.'); setPage(1); setNotice(`${Number(result.deleted || 0).toLocaleString()} scheduled payments deleted from CharityPro. Sola was not changed.`); await load(true); } catch (e: any) { setError(e.message || 'Unable to delete all schedules.'); } finally { setDeletingAll(false); } };

  return <main style={{ minHeight: '100vh', background: 'var(--bg)', padding: 28, fontFamily: 'Inter, sans-serif' }}><div style={{ maxWidth: 1400, margin: '0 auto' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 20, marginBottom: 22 }}><div><div style={{ color: 'var(--green)', fontWeight: 800, fontSize: 13 }}>CHARITYPRO CLOUD</div><h1 style={{ color: 'var(--navy)', margin: '4px 0' }}>Schedules ({total.toLocaleString()})</h1><div style={{ color: 'var(--text-muted)' }}>Recurring payments shared online · 50 records per page</div></div><div style={{display:'flex',gap:8}}><button className="btn btn-danger" disabled={!total||deletingAll} onClick={()=>void removeAll()}>{deletingAll?'Deleting...':'Delete all scheduled payments'}</button><button className="btn btn-primary" onClick={beginNew}>New Schedule</button></div></div>
    {editing && <div className="modal-overlay" onClick={() => setEditing(false)}><form className="modal" onClick={event => event.stopPropagation()} onSubmit={save} style={{ maxWidth: 820, width: '92%' }}><div className="modal-header"><h2 style={{ margin: 0, color: 'var(--navy)' }}>{form.id ? 'Edit Schedule' : 'New Schedule'}</h2><button type="button" className="modal-close" onClick={() => setEditing(false)}>×</button></div><div className="modal-body"><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: 14 }}>
      <label className="form-group" style={{ margin: 0 }}><span>Find donor</span><input value={donorSearch} onChange={event => setDonorSearch(event.target.value)} placeholder="Type a donor name" /></label><label className="form-group" style={{ margin: 0 }}><span>Donor *</span><select value={form.donorId} onChange={event => setForm(current => ({ ...current, donorId: event.target.value }))}><option value="">Select from up to 50 matches</option>{donors.map(donor => <option key={donor.id} value={donor.id}>{donor.name}</option>)}</select></label>
      <label className="form-group" style={{ margin: 0 }}><span>Amount *</span><input type="number" min="0.01" step="0.01" value={form.amount} onChange={event => setForm(current => ({ ...current, amount: event.target.value }))} /></label><label className="form-group" style={{ margin: 0 }}><span>Currency</span><select value={form.currency} onChange={event => setForm(current => ({ ...current, currency: event.target.value as 'CAD' | 'USD' }))}><option>CAD</option><option>USD</option></select></label>
      <label className="form-group" style={{ margin: 0 }}><span>Frequency</span><select value={form.frequency} onChange={event => setForm(current => ({ ...current, frequency: event.target.value as any }))}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label className="form-group" style={{ margin: 0 }}><span>Payment method</span><select value={form.method} onChange={event => setForm(current => ({ ...current, method: event.target.value }))}><option value="credit_card">Credit card</option><option value="check">Check</option><option value="cash">Cash</option><option value="e_transfer">E-transfer</option><option value="other">Other</option></select></label>
      <label className="form-group" style={{ margin: 0 }}><span>Next date *</span><input type="date" value={form.nextDate} onChange={event => setForm(current => ({ ...current, nextDate: event.target.value }))} /></label><label className="form-group" style={{ margin: 0 }}><span>End date</span><input type="date" value={form.endDate} onChange={event => setForm(current => ({ ...current, endDate: event.target.value }))} /></label><label style={{ display: 'flex', alignItems: 'center', gap: 8 }}><input type="checkbox" checked={form.active} onChange={event => setForm(current => ({ ...current, active: event.target.checked }))} /> Active</label>
    </div></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={() => setEditing(false)}>Cancel</button><button className="btn btn-primary">Save Schedule</button></div></form></div>}
    {notice && <div className="card" style={{ padding: 14, color: 'var(--green)', fontWeight: 800, marginBottom: 16 }}>{notice}</div>}{error && <div className="card" style={{ padding: 14, color: 'var(--red)', fontWeight: 700, marginBottom: 16 }}>{error}</div>}
    <section className="card" style={{ padding: 0, overflow: 'hidden' }}>
      <div className="filter-strip"><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Live search donor, amount, method or frequency" /><select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="all">All schedules</option><option value="active">Active</option><option value="paused">Paused</option></select><input type="date" value={from} onChange={event=>{setFrom(event.target.value);setPage(1);}} title="Next date from"/><input type="date" value={to} onChange={event=>{setTo(event.target.value);setPage(1);}} title="Next date to"/></div>
      {loading ? <div style={{ padding: 40, textAlign: 'center' }}>Loading schedules...</div> : <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr>
        <SortableTh column="nextDate" label="Next date" sort={sort} direction={direction} onSort={changeSort}/><SortableTh column="donor" label="Donor" sort={sort} direction={direction} onSort={changeSort}/><SortableTh column="frequency" label="Frequency" sort={sort} direction={direction} onSort={changeSort}/><th>Payments left</th><th>End date</th><SortableTh column="method" label="Method" sort={sort} direction={direction} onSort={changeSort}/><SortableTh column="status" label="Status" sort={sort} direction={direction} onSort={changeSort}/><SortableTh column="amount" label="Amount" sort={sort} direction={direction} onSort={changeSort} align="right"/><th />
      </tr></thead><tbody>{items.map(item => <tr key={item.id} onClick={() => setSelectedSchedule(item)} style={{ cursor: 'pointer' }}><td>{item.nextDate}</td><td style={{ fontWeight: 800 }}>{item.donorName}</td><td>{item.frequency}</td><td>{item.paymentsRemaining||'—'}</td><td>{item.endDate||'No fixed end'}</td><td>{item.method.replace('_', ' ')}</td><td>{item.active ? 'Active' : 'Paused'}</td><td style={{ textAlign: 'right', fontWeight: 800 }}>{item.currency} ${item.amount.toFixed(2)}</td><td style={{ textAlign: 'right' }}><button className="btn btn-secondary btn-sm" onClick={event => { event.stopPropagation(); void toggle(item); }}>{item.active ? 'Pause' : 'Resume'}</button> <button className="btn btn-secondary btn-sm" onClick={event => { event.stopPropagation(); beginEdit(item); }}>Edit</button> <button className="btn btn-danger btn-sm" onClick={event => { event.stopPropagation(); void remove(item); }}>Delete</button></td></tr>)}{items.length === 0 && <tr><td colSpan={9} style={{ padding: 30, textAlign: 'center' }}>No matching schedules.</td></tr>}</tbody></table></div>}
      <div style={{ display: 'flex', justifyContent: 'space-between', padding: 14, borderTop: '1px solid var(--border)' }}><span>Page {page} of {totalPages}</span><div style={{ display: 'flex', gap: 8 }}><button className="btn btn-secondary btn-sm" disabled={page <= 1 || loading} onClick={() => setPage(value => Math.max(1, value - 1))}>Previous</button><button className="btn btn-secondary btn-sm" disabled={page >= totalPages || loading} onClick={() => setPage(value => Math.min(totalPages, value + 1))}>Next</button></div></div>
    </section>
    {selectedSchedule && <CloudScheduleDetailsModal schedule={selectedSchedule} onClose={() => setSelectedSchedule(null)} onUpdated={schedule => { setSelectedSchedule(schedule); void load(true); }} />}
  </div></main>;
};
