import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Check, Download, FileText, Pencil, Plus, Trash2, User, Users, X } from 'lucide-react';
import { CloudBillDetailsModal } from '../components/CloudBillDetailsModal';

type Tab = 'employees' | 'fundraisers' | 't4a' | 'schedules';
type Entity = { id: string; revision: number; name: string; role?: string; email?: string; phone?: string; percentage?: number; internalAccountBalance?: number; balanceOwed: number };
type T4A = { id: string; revision: number; entityId: string; entityType: 'employee' | 'fundraiser'; year: number; box48Amount: number; issuedDate: string };
type Schedule = { id: string; revision: number; entityId: string; type: 'employee' | 'fundraiser'; amount: number; earningType: string; t4aEligible: boolean; frequency: 'weekly' | 'biweekly' | 'monthly'; startDate: string; nextDate: string; active: boolean };
type Account = { id: string; name: string; type: string; balance?: number };

const money = (value: number) => Number(value || 0).toFixed(2);

export const OnlinePayroll: React.FC = () => {
  const [activeTab,setActiveTab]=useState<Tab>('employees'); const [employees,setEmployees]=useState<Entity[]>([]); const [fundraisers,setFundraisers]=useState<Entity[]>([]); const [t4as,setT4as]=useState<T4A[]>([]); const [schedules,setSchedules]=useState<Schedule[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [page,setPage]=useState(1); const [totalPages,setTotalPages]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [search,setSearch]=useState('');
  const [employeeForm,setEmployeeForm]=useState<({id?:string;revision?:number;name:string;role:string;email:string})|null>(null); const [entryTarget,setEntryTarget]=useState<(Entity&{entityType:'employee'|'fundraiser';action:'earnings'|'payment'})|null>(null); const [entryForm,setEntryForm]=useState({amount:'',date:new Date().toISOString().slice(0,10),earningType:'Salary',sourceAccountId:'',t4aEligible:false,recurring:false,frequency:'monthly'}); const [t4aForm,setT4aForm]=useState<(Partial<T4A>&{entityName:string})|null>(null); const [scheduleForm,setScheduleForm]=useState<Schedule|null>(null); const [ledgerTarget,setLedgerTarget]=useState<(Entity&{entityType:'employee'|'fundraiser'})|null>(null); const [ledger,setLedger]=useState<any[]>([]); const [ledgerPage,setLedgerPage]=useState(1); const [ledgerPages,setLedgerPages]=useState(1); const [selectedBill,setSelectedBill]=useState<any|null>(null); const requestId=useRef('');

  const load = useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const encoded=encodeURIComponent(search);const [employeeResponse,fundraiserResponse,accountResponse]=await Promise.all([fetch(`/api/v3/payroll/entities?type=employees&page=${activeTab==='employees'?page:1}&limit=50&search=${encoded}`),fetch(`/api/v3/payroll/entities?type=fundraisers&page=${activeTab==='fundraisers'?page:1}&limit=50&search=${encoded}`),fetch('/api/v3/accounts?limit=50')]);const [employeeData,fundraiserData,accountData]=await Promise.all([employeeResponse.json(),fundraiserResponse.json(),accountResponse.json()]);if(!employeeResponse.ok||!fundraiserResponse.ok)throw new Error(employeeData.error||fundraiserData.error||'Unable to load payroll.');setEmployees(employeeData.items||[]);setFundraisers(fundraiserData.items||[]);if(accountData.success)setAccounts(accountData.items||[]);if(activeTab==='employees')setTotalPages(Math.max(1,employeeData.totalPages||1));else if(activeTab==='fundraisers')setTotalPages(Math.max(1,fundraiserData.totalPages||1));else{const collection=activeTab==='t4a'?'t4aSlips':'recurringPayroll';const response=await fetch(`/api/v3/records/${collection}?page=${page}&limit=50&search=${encoded}`);const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to load payroll records.');if(activeTab==='t4a')setT4as(data.items||[]);else setSchedules(data.items||[]);setTotalPages(Math.max(1,data.totalPages||1));}setError('');}catch(reason:any){if(!silent)setError(reason.message||'Unable to load payroll.');}finally{if(!silent)setLoading(false);}},[activeTab,page,search]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),3000);return()=>window.clearInterval(timer);},[load]);
  const names=useMemo(()=>new Map([...employees.map(item=>[item.id,item.name] as const),...fundraisers.map(item=>[item.id,item.name] as const)]),[employees,fundraisers]);
  const changeTab=(tab:Tab)=>{setActiveTab(tab);setPage(1);setError('');};
  const recordMutation=async(collection:string,item:any,method:'POST'|'PUT'|'DELETE',data?:any)=>{const key=crypto.randomUUID();const response=await fetch(method==='POST'?`/api/v3/records/${collection}`:`/api/v3/records/${collection}/${encodeURIComponent(item.id)}`,{method,headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(method==='POST'?{data}:method==='PUT'?{revision:item.revision,data}:{revision:item.revision})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Unable to save this payroll record.');return result.item;};
  const saveEmployee=async(event:React.FormEvent)=>{event.preventDefault();if(!employeeForm)return;try{if(employeeForm.id)await recordMutation('employees',employeeForm,'PUT',{name:employeeForm.name.trim(),role:employeeForm.role.trim(),email:employeeForm.email.trim()});else await recordMutation('employees',{},'POST',{name:employeeForm.name.trim(),role:employeeForm.role.trim(),email:employeeForm.email.trim(),balanceOwed:0});setEmployeeForm(null);await load(true);}catch(reason:any){setError(reason.message);}};
  const removeRecord=async(collection:string,item:any,label:string)=>{if(!window.confirm(`Delete ${label}?`))return;try{await recordMutation(collection,item,'DELETE');await load(true);}catch(reason:any){setError(reason.message);}};
  const openEntry=(entity:Entity,entityType:'employee'|'fundraiser',action:'earnings'|'payment')=>{setEntryTarget({...entity,entityType,action});setEntryForm({amount:'',date:new Date().toISOString().slice(0,10),earningType:'Salary',sourceAccountId:'',t4aEligible:false,recurring:false,frequency:'monthly'});setError('');requestId.current='';};
  const saveEntry=async(event:React.FormEvent)=>{event.preventDefault();if(!entryTarget)return;const key=requestId.current||crypto.randomUUID();requestId.current=key;try{const response=await fetch('/api/v3/payroll/entries',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({action:entryTarget.action,entityId:entryTarget.id,entityType:entryTarget.entityType,amount:Number(entryForm.amount),date:entryForm.date,earningType:entryForm.earningType,sourceAccountId:entryForm.sourceAccountId,t4aEligible:entryForm.t4aEligible,recurring:entryForm.recurring,frequency:entryForm.frequency})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to record payroll.');requestId.current='';setEntryTarget(null);await load(true);}catch(reason:any){requestId.current='';setError(reason.message||'Unable to record payroll.');}};
  const openT4a=(entity:Entity,entityType:'employee'|'fundraiser')=>setT4aForm({entityId:entity.id,entityType,entityName:entity.name,year:new Date().getFullYear(),box48Amount:0,issuedDate:new Date().toISOString().slice(0,10)});
  const saveT4a=async(event:React.FormEvent)=>{event.preventDefault();if(!t4aForm)return;try{if(t4aForm.id)await recordMutation('t4aSlips',t4aForm,'PUT',{year:Number(t4aForm.year),box48Amount:Number(t4aForm.box48Amount)});else await recordMutation('t4aSlips',{},'POST',{entityId:t4aForm.entityId,entityType:t4aForm.entityType,year:Number(t4aForm.year),box48Amount:Number(t4aForm.box48Amount),issuedDate:t4aForm.issuedDate});setT4aForm(null);setActiveTab('t4a');setPage(1);await load(true);}catch(reason:any){setError(reason.message);}};
  const saveSchedule=async(event:React.FormEvent)=>{event.preventDefault();if(!scheduleForm)return;try{await recordMutation('recurringPayroll',scheduleForm,'PUT',{amount:Number(scheduleForm.amount),earningType:scheduleForm.earningType,t4aEligible:scheduleForm.t4aEligible,frequency:scheduleForm.frequency,startDate:scheduleForm.startDate,nextDate:scheduleForm.nextDate,active:scheduleForm.active});setScheduleForm(null);await load(true);}catch(reason:any){setError(reason.message);}};
  const openLedger=async(entity:Entity,entityType:'employee'|'fundraiser')=>{setLedgerTarget({...entity,entityType});setLedgerPage(1);setLedger([]);setError('');};
  useEffect(()=>{if(!ledgerTarget)return;fetch(`/api/v3/payroll/${ledgerTarget.entityType}/${ledgerTarget.id}/ledger?page=${ledgerPage}&limit=50`).then(async response=>{const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error);setLedger(data.items||[]);setLedgerPages(Math.max(1,data.totalPages||1));}).catch(reason=>setError(reason.message||'Unable to load payroll ledger.'));},[ledgerTarget,ledgerPage]);
  const exportT4a=()=>{const rows=[['Tax Year','Entity Type','Recipient Name','Box 48','Date Issued'],...t4as.map(item=>[item.year,item.entityType,names.get(item.entityId)||'Unknown',item.box48Amount,item.issuedDate])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download=`charitypro-t4a-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);};
  const tabs:[Tab,string,React.ElementType,string][]=[['employees','Office Staff',User,'var(--navy)'],['fundraisers','Fundraisers / Contractors',Users,'var(--navy)'],['t4a','T4A Tax Slips',FileText,'var(--purple)'],['schedules','Recurring Schedules',Check,'var(--green)']];

  return <div style={{display:'grid',gap:24}}><div className="card" style={{padding:0}}><div style={{display:'flex',borderBottom:'1px solid var(--border)',background:'var(--bg-input)',borderTopLeftRadius:12,borderTopRightRadius:12,overflowX:'auto'}}>{tabs.map(([key,label,Icon,color])=><button key={key} onClick={()=>changeTab(key)} style={{padding:'16px 24px',background:activeTab===key?'var(--bg)':'transparent',border:'none',borderBottom:activeTab===key?`2px solid ${color}`:'2px solid transparent',color:activeTab===key?color:'var(--text-muted)',fontWeight:activeTab===key?700:500,cursor:'pointer',display:'flex',alignItems:'center',gap:8,whiteSpace:'nowrap'}}><Icon size={16}/>{label}</button>)}</div><div style={{padding:24}}><div style={{marginBottom:18}}><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}} placeholder="Live search names, roles, email, tax slips or schedules"/></div>{error&&!employeeForm&&!entryTarget&&!t4aForm&&!scheduleForm&&<div style={{color:'var(--red)',fontWeight:700,marginBottom:14}}>{error}</div>}{loading?<div style={{padding:40,textAlign:'center'}}>Loading payroll...</div>:<>
    {activeTab==='employees'&&<EntityTable title="Office Staff Payroll" items={employees} type="employee" onAdd={()=>setEmployeeForm({name:'',role:'',email:''})} onLedger={openLedger} onEntry={openEntry} onT4a={openT4a} onEdit={item=>setEmployeeForm({id:item.id,revision:item.revision,name:item.name,role:item.role||'',email:item.email||''})} onDelete={item=>void removeRecord('employees',item,item.name)}/>} 
    {activeTab==='fundraisers'&&<EntityTable title="Fundraisers Ledger" items={fundraisers} type="fundraiser" onLedger={openLedger} onEntry={openEntry} onT4a={openT4a}/>} 
    {activeTab==='t4a'&&<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><div><h2 style={{margin:0,color:'var(--navy)'}}>T4A Tax Slips</h2><div style={{color:'var(--text-muted)',fontSize:'.9rem',marginTop:4}}>Year-end export for your accountant. Box 48: Fees for Services.</div></div><button className="btn btn-secondary" onClick={exportT4a}><Download size={16}/> Export to Accountant</button></div><div className="table-container"><table><thead><tr><th>Tax Year</th><th>Entity Type</th><th>Recipient Name</th><th>Box 48 (Fee for Service)</th><th>Date Issued</th><th style={{textAlign:'right'}}>Actions</th></tr></thead><tbody>{t4as.map(item=><tr key={item.id} onClick={()=>setT4aForm({...item,entityName:names.get(item.entityId)||'Unknown'})} style={{cursor:'pointer'}}><td><strong>{item.year}</strong></td><td style={{textTransform:'capitalize'}}>{item.entityType}</td><td><strong>{names.get(item.entityId)||'Unknown'}</strong></td><td style={{fontWeight:700,color:'var(--purple)'}}>${money(item.box48Amount)}</td><td>{item.issuedDate}</td><td style={{textAlign:'right'}}><button className="btn btn-ghost btn-sm" onClick={event=>{event.stopPropagation();setT4aForm({...item,entityName:names.get(item.entityId)||'Unknown'});}}><Pencil size={14}/></button><button className="btn btn-ghost btn-sm" style={{color:'var(--red)'}} onClick={event=>{event.stopPropagation();void removeRecord('t4aSlips',item,`T4A for ${names.get(item.entityId)||'recipient'}`);}}><Trash2 size={14}/></button></td></tr>)}{!t4as.length&&<tr><td colSpan={6} style={{textAlign:'center',padding:20,color:'var(--text-muted)'}}>No T4A slips generated yet.</td></tr>}</tbody></table></div></>}
    {activeTab==='schedules'&&<><h2 style={{margin:'0 0 20px',color:'var(--navy)'}}>Recurring Payroll Schedules</h2><div className="table-container"><table><thead><tr><th>Entity</th><th>Type</th><th>Frequency</th><th>Start Date</th><th>Next Date</th><th style={{textAlign:'right'}}>Amount</th><th style={{textAlign:'right'}}>Status</th><th style={{textAlign:'right'}}>Actions</th></tr></thead><tbody>{schedules.map(item=><tr key={item.id} onClick={()=>setScheduleForm(item)} style={{cursor:'pointer'}}><td><strong>{names.get(item.entityId)||'Unknown'}</strong></td><td style={{textTransform:'capitalize'}}>{item.earningType}</td><td style={{textTransform:'capitalize'}}>{item.frequency}</td><td>{item.startDate}</td><td>{item.nextDate}</td><td style={{textAlign:'right',fontWeight:700}}>${money(item.amount)}</td><td style={{textAlign:'right'}}><button className={`badge ${item.active?'badge-green':'badge-yellow'}`} style={{border:'none',cursor:'pointer'}} onClick={async event=>{event.stopPropagation();try{await recordMutation('recurringPayroll',item,'PUT',{active:!item.active});await load(true);}catch(reason:any){setError(reason.message);}}}>{item.active?'Active':'Paused'}</button></td><td style={{textAlign:'right'}}><button className="btn btn-ghost btn-sm" onClick={event=>{event.stopPropagation();setScheduleForm(item);}}><Pencil size={14}/></button><button className="btn btn-ghost btn-sm" style={{color:'var(--red)'}} onClick={event=>{event.stopPropagation();void removeRecord('recurringPayroll',item,'this recurring schedule');}}><Trash2 size={14}/></button></td></tr>)}{!schedules.length&&<tr><td colSpan={8} style={{textAlign:'center',padding:20,color:'var(--text-muted)'}}>No recurring schedules found.</td></tr>}</tbody></table></div></>}
  </>}</div>{totalPages>1&&<div style={{display:'flex',justifyContent:'space-between',padding:'0 24px 20px'}}><span>Page {page} of {totalPages} · 50 records maximum</span><div style={{display:'flex',gap:8}}><button className="btn btn-secondary btn-sm" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><button className="btn btn-secondary btn-sm" disabled={page>=totalPages} onClick={()=>setPage(value=>value+1)}>Next</button></div></div>}</div>
  {employeeForm&&<Modal title={employeeForm.id?'Edit Employee':'Add Office Staff'} onClose={()=>setEmployeeForm(null)}><form onSubmit={saveEmployee} style={{display:'grid',gap:16}}><Field label="Name"><input required value={employeeForm.name} onChange={event=>setEmployeeForm({...employeeForm,name:event.target.value})}/></Field><Field label="Role / Title"><input required value={employeeForm.role} onChange={event=>setEmployeeForm({...employeeForm,role:event.target.value})}/></Field><Field label="Email (Optional)"><input type="email" value={employeeForm.email} onChange={event=>setEmployeeForm({...employeeForm,email:event.target.value})}/></Field><Footer onCancel={()=>setEmployeeForm(null)} label={employeeForm.id?'Save Changes':'Save Employee'}/></form></Modal>}
  {entryTarget&&<Modal title={`${entryTarget.action==='payment'?'Record Payment to':'Add Earnings for'} ${entryTarget.name}`} onClose={()=>setEntryTarget(null)}><form onSubmit={saveEntry} style={{display:'grid',gap:16}}>{error&&<div style={{color:'var(--red)',fontWeight:700}}>{error}</div>}<div style={{background:'var(--bg-input)',padding:16,borderRadius:8}}>Current Balance Owed: <strong>${money(entryTarget.balanceOwed)}</strong></div>{entryTarget.action==='earnings'&&<Field label="Earning Type"><select value={entryForm.earningType} onChange={event=>setEntryForm({...entryForm,earningType:event.target.value})}>{['Salary','Hourly','Bonus','Tip','Commission','Other'].map(value=><option key={value}>{value}</option>)}</select></Field>}<Field label="Date"><input type="date" required value={entryForm.date} onChange={event=>setEntryForm({...entryForm,date:event.target.value})}/></Field>{entryTarget.action==='payment'&&<Field label="Paid From Bank Account"><select required value={entryForm.sourceAccountId} onChange={event=>setEntryForm({...entryForm,sourceAccountId:event.target.value})}><option value="">-- Select Bank Account --</option>{accounts.filter(account=>account.type==='asset'||account.type==='liability').map(account=><option key={account.id} value={account.id}>{account.name} (${money(account.balance||0)})</option>)}</select></Field>}<Field label={`${entryTarget.action==='payment'?'Amount Paid':'Earnings Amount'} ($)`}><input type="number" min=".01" step=".01" required value={entryForm.amount} onChange={event=>setEntryForm({...entryForm,amount:event.target.value})}/></Field>{entryTarget.action==='payment'?<label style={{display:'flex',gap:8}}><input type="checkbox" checked={entryForm.t4aEligible} onChange={event=>setEntryForm({...entryForm,t4aEligible:event.target.checked})}/> Include this payment in T4A (Box 48 Eligible)</label>:<div style={{background:'var(--bg-input)',padding:16,borderRadius:8}}><label style={{display:'flex',gap:8,fontWeight:600}}><input type="checkbox" checked={entryForm.recurring} onChange={event=>setEntryForm({...entryForm,recurring:event.target.checked})}/> Make this a recurring payroll entry</label>{entryForm.recurring&&<Field label="Frequency"><select value={entryForm.frequency} onChange={event=>setEntryForm({...entryForm,frequency:event.target.value})}><option value="weekly">Weekly</option><option value="biweekly">Bi-weekly</option><option value="monthly">Monthly</option></select></Field>}</div>}<Footer onCancel={()=>setEntryTarget(null)} label={entryTarget.action==='payment'?'Record Payment':'Add Earnings'}/></form></Modal>}
  {t4aForm&&<Modal title={`${t4aForm.id?'Edit':'Generate'} T4A for ${t4aForm.entityName}`} onClose={()=>setT4aForm(null)}><form onSubmit={saveT4a} style={{display:'grid',gap:16}}><Field label="Tax Year"><input type="number" min="2000" max="2100" required value={t4aForm.year||''} onChange={event=>setT4aForm({...t4aForm,year:Number(event.target.value)})}/></Field><Field label="Box 48 Amount (Fees for Services)"><input type="number" min="0" step=".01" required value={t4aForm.box48Amount||''} onChange={event=>setT4aForm({...t4aForm,box48Amount:Number(event.target.value)})}/></Field><Footer onCancel={()=>setT4aForm(null)} label={t4aForm.id?'Save Changes':'Generate T4A'}/></form></Modal>}
  {scheduleForm&&<Modal title="Edit Recurring Payroll Schedule" onClose={()=>setScheduleForm(null)}><form onSubmit={saveSchedule} style={{display:'grid',gap:16}}><Field label="Earning Type"><input value={scheduleForm.earningType} onChange={event=>setScheduleForm({...scheduleForm,earningType:event.target.value})}/></Field><Field label="Amount"><input type="number" min=".01" step=".01" value={scheduleForm.amount} onChange={event=>setScheduleForm({...scheduleForm,amount:Number(event.target.value)})}/></Field><Field label="Frequency"><select value={scheduleForm.frequency} onChange={event=>setScheduleForm({...scheduleForm,frequency:event.target.value as Schedule['frequency']})}><option value="weekly">Weekly</option><option value="biweekly">Bi-weekly</option><option value="monthly">Monthly</option></select></Field><Field label="Start Date"><input type="date" value={scheduleForm.startDate} onChange={event=>setScheduleForm({...scheduleForm,startDate:event.target.value})}/></Field><Field label="Next Date"><input type="date" value={scheduleForm.nextDate} onChange={event=>setScheduleForm({...scheduleForm,nextDate:event.target.value})}/></Field><label style={{display:'flex',gap:8}}><input type="checkbox" checked={scheduleForm.active} onChange={event=>setScheduleForm({...scheduleForm,active:event.target.checked})}/> Active</label><Footer onCancel={()=>setScheduleForm(null)} label="Save All Changes"/></form></Modal>}
  {ledgerTarget&&<Modal title={`Ledger for ${ledgerTarget.name}`} onClose={()=>setLedgerTarget(null)} large><div className="table-container"><table><thead><tr><th>Date</th><th>Description</th><th>Type</th><th style={{textAlign:'right'}}>Amount</th><th style={{textAlign:'right'}}>Actions</th></tr></thead><tbody>{ledger.map(bill=><tr key={bill.id} onClick={()=>setSelectedBill(bill)} style={{cursor:'pointer'}}><td>{bill.status==='paid'?(bill.paidDate||bill.dueDate):bill.dueDate}</td><td>{bill.memo||bill.earningType||(bill.status==='paid'?'Payment (Bank)':'Earnings Added')}</td><td><span className={`badge ${bill.status==='paid'?'badge-green':'badge-purple'}`}>{bill.status==='paid'?'Payment':'Earnings'}</span></td><td style={{textAlign:'right',fontWeight:700,color:bill.status==='paid'?'var(--green)':'var(--navy)'}}>{bill.status==='paid'?'-':'+'}${money(bill.amount)}</td><td style={{textAlign:'right'}}><button className="btn btn-ghost btn-sm" onClick={event=>{event.stopPropagation();setSelectedBill(bill);}}><Pencil size={14}/></button><button className="btn btn-ghost btn-sm" style={{color:'var(--red)'}} onClick={event=>{event.stopPropagation();void removeRecord('bills',bill,'this ledger entry').then(()=>setLedgerTarget({...ledgerTarget}));}}><Trash2 size={14}/></button></td></tr>)}{!ledger.length&&<tr><td colSpan={5} style={{textAlign:'center',padding:20,color:'var(--text-muted)'}}>No history available.</td></tr>}</tbody></table></div>{ledgerPages>1&&<div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><button className="btn btn-secondary btn-sm" disabled={ledgerPage<=1} onClick={()=>setLedgerPage(value=>value-1)}>Previous</button><span>Page {ledgerPage} of {ledgerPages}</span><button className="btn btn-secondary btn-sm" disabled={ledgerPage>=ledgerPages} onClick={()=>setLedgerPage(value=>value+1)}>Next</button></div>}</Modal>}
  {selectedBill&&<CloudBillDetailsModal bill={selectedBill} onClose={()=>setSelectedBill(null)} onUpdated={updated=>{setSelectedBill(updated);setLedger(current=>current.map(item=>item.id===updated.id?updated:item));void load(true);}}/>}
  </div>;
};

const EntityTable:React.FC<{title:string;items:Entity[];type:'employee'|'fundraiser';onAdd?:()=>void;onLedger:(item:Entity,type:'employee'|'fundraiser')=>void;onEntry:(item:Entity,type:'employee'|'fundraiser',action:'earnings'|'payment')=>void;onT4a:(item:Entity,type:'employee'|'fundraiser')=>void;onEdit?:(item:Entity)=>void;onDelete?:(item:Entity)=>void}>=({title,items,type,onAdd,onLedger,onEntry,onT4a,onEdit,onDelete})=><><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><h2 style={{margin:0,color:'var(--navy)'}}>{title}</h2>{onAdd&&<button className="btn btn-primary" onClick={onAdd}><Plus size={16}/> Add Employee</button>}</div><div className="table-container"><table><thead><tr><th>Name</th>{type==='employee'?<><th>Role</th><th>Email</th></>:<><th>Commission %</th><th>Internal Balance (Accrued)</th></>}<th>Balance Owed</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>onLedger(item,type)} style={{cursor:'pointer'}}><td><strong>{item.name}</strong></td>{type==='employee'?<><td>{item.role}</td><td>{item.email||'-'}</td></>:<><td>{item.percentage||0}%</td><td style={{fontWeight:600,color:'var(--navy)'}}>${money(item.internalAccountBalance||0)}</td></>}<td style={{fontWeight:700,color:item.balanceOwed<0?'var(--green)':'var(--red)'}}>{item.balanceOwed<0?`(Credit: $${money(Math.abs(item.balanceOwed))})`:`$${money(item.balanceOwed)}`}</td><td><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btn-primary btn-sm" onClick={event=>{event.stopPropagation();onEntry(item,type,'earnings');}}>Add Earnings</button><button className="btn btn-secondary btn-sm" onClick={event=>{event.stopPropagation();onEntry(item,type,'payment');}}>Record Payment</button><button className="btn btn-ghost btn-sm" onClick={event=>{event.stopPropagation();onT4a(item,type);}}>Generate T4A</button>{onEdit&&<button className="btn btn-ghost btn-sm" onClick={event=>{event.stopPropagation();onEdit(item);}}><Pencil size={14}/></button>}{onDelete&&<button className="btn btn-ghost btn-sm" style={{color:'var(--red)'}} onClick={event=>{event.stopPropagation();onDelete(item);}}><Trash2 size={14}/></button>}</div></td></tr>)}{!items.length&&<tr><td colSpan={5} style={{textAlign:'center',padding:20,color:'var(--text-muted)'}}>No {type==='employee'?'office staff':'fundraisers'} added.</td></tr>}</tbody></table></div></>;
const Modal:React.FC<{title:string;onClose:()=>void;large?:boolean;children:React.ReactNode}>=({title,onClose,large,children})=><div className="modal-overlay" onClick={onClose}><div className={`modal${large?' modal-lg':''}`} onClick={event=>event.stopPropagation()}><div className="modal-header"><h2>{title}</h2><button className="modal-close" onClick={onClose}><X size={20}/></button></div><div className="modal-body">{children}</div></div></div>;
const Field:React.FC<{label:string;children:React.ReactNode}>=({label,children})=><label className="form-group" style={{margin:0}}><span>{label}</span>{children}</label>;
const Footer:React.FC<{onCancel:()=>void;label:string}>=({onCancel,label})=><div className="modal-footer" style={{marginTop:8}}><button type="button" className="btn btn-secondary" onClick={onCancel}>Cancel</button><button className="btn btn-primary">{label}</button></div>;
