import React, { useCallback, useEffect, useState } from 'react';
import { Search } from 'lucide-react';
import { CloudBillDetailsModal } from '../components/CloudBillDetailsModal';
import { CloudPaymentDetailsModal } from '../components/CloudPaymentDetailsModal';
import { CloudTransferDetailsModal } from '../components/CloudTransferDetailsModal';

type Item = { id: string; revision: number; recordType: 'transactions' | 'bills' | 'accountTransfers'; amount: number; currency?: string; date?: string; dueDate?: string; paidDate?: string; donorName?: string; vendor?: string; notes?: string; memo?: string; type?: string; status?: string; method?: string; sourceName?: string; offsetName?: string; [key: string]: any };
type Account = { id: string; name: string };
const money = (value: number) => Number(value || 0).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export const OnlineTransactions: React.FC = () => {
  const [items, setItems] = useState<Item[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<Item | null>(null);
  const [search, setSearch] = useState(''); const [kind, setKind] = useState('all'); const [account, setAccount] = useState(''); const [status, setStatus] = useState(''); const [method, setMethod] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  useEffect(() => { fetch('/api/v3/accounts?limit=100').then(response => response.json()).then(data => { if (data.success) setAccounts(data.items); }).catch(() => undefined); }, []);
  const load = useCallback(async (silent = false) => { if (!silent) { setLoading(true); setError(''); } const params = new URLSearchParams({ page: String(page), limit: '50', search, kind, account, status, method, from, to }); try { const response = await fetch(`/api/v3/ledger?${params.toString()}`); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Unable to load transactions.'); setItems(data.items); setTotal(Number(data.total || 0)); setTotalPages(Math.max(1, Number(data.totalPages || 1))); } catch (reason: any) { if (!silent) setError(reason.message || 'Unable to load transactions.'); } finally { if (!silent) setLoading(false); } }, [page, search, kind, account, status, method, from, to]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(true), 3000); return () => window.clearInterval(timer); }, [load]);
  const resetPage = () => setPage(1); const date = (item: Item) => item.date || item.paidDate || item.dueDate || ''; const label = (item: Item) => item.recordType === 'transactions' ? (item.donorName || item.notes || 'Donation / Income') : item.recordType === 'bills' ? (item.vendor || 'Expense') : (item.notes || 'Account Transfer'); const typeLabel = (item: Item) => item.recordType === 'transactions' ? (item.isBatch ? 'Batch Deposit' : 'Payment') : item.recordType === 'bills' ? 'Bill / Expense' : 'Transfer';
  const updateSelected = (updated: any) => { const next = { ...selected, ...updated } as Item; setSelected(next); setItems(current => current.map(item => item.id === next.id && item.recordType === next.recordType ? next : item)); void load(true); };
  return <main style={{ minHeight: '100vh', background: 'var(--bg)', padding: 28 }}><div style={{ maxWidth: 1500, margin: '0 auto' }}><div style={{ marginBottom: 22 }}><div style={{ color: 'var(--green)', fontWeight: 800, fontSize: 13 }}>CHARITYPRO CLOUD</div><h1 style={{ color: 'var(--navy)', margin: '4px 0' }}>Master Transactions Ledger ({total.toLocaleString()})</h1><div style={{ color: 'var(--text-muted)' }}>Payments, expenses, and account transfers · 50 records per page</div></div>
    <section className="card" style={{ padding: 16, marginBottom: 18 }}><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><div className="search-box" style={{ width: 260 }}><Search className="search-icon" size={18} /><input value={search} onChange={event => { setSearch(event.target.value); resetPage(); }} placeholder="Search transactions..." /></div><select value={kind} onChange={event => { setKind(event.target.value); resetPage(); }}><option value="all">All Records</option><option value="payment">Payments</option><option value="bill">Bills / Expenses</option><option value="transfer">Transfers</option></select><select value={account} onChange={event => { setAccount(event.target.value); resetPage(); }}><option value="">All Accounts</option>{accounts.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={method} onChange={event => { setMethod(event.target.value); resetPage(); }}><option value="">All Methods</option><option value="credit_card">Credit Card</option><option value="check">Check</option><option value="cash">Cash</option><option value="e_transfer">E-Transfer</option><option value="other">Other</option></select><select value={status} onChange={event => { setStatus(event.target.value); resetPage(); }}><option value="">All Statuses</option><option value="approved">Approved</option><option value="pending">Pending</option><option value="urgent">Urgent</option><option value="paid">Paid</option><option value="declined">Declined</option></select><input type="date" aria-label="From date" value={from} onChange={event => { setFrom(event.target.value); resetPage(); }} /><input type="date" aria-label="To date" value={to} onChange={event => { setTo(event.target.value); resetPage(); }} /></div></section>
    {error && <div className="card" style={{ padding: 14, color: 'var(--red)', fontWeight: 700, marginBottom: 16 }}>{error}</div>}<section className="card" style={{ padding: 0, overflow: 'hidden' }}>{loading ? <div style={{ padding: 40, textAlign: 'center' }}>Loading shared ledger...</div> : <div style={{ overflowX: 'auto' }}><table style={{ width: '100%' }}><thead><tr><th>Date</th><th>Type</th><th>Name / Description</th><th>Status</th><th>Source Account</th><th>Offset Account</th><th style={{ textAlign: 'right' }}>Amount</th></tr></thead><tbody>{items.map(item => <tr key={`${item.recordType}-${item.id}`} onClick={() => setSelected(item)} style={{ cursor: 'pointer' }}><td>{date(item)}</td><td><span className="badge badge-gray">{typeLabel(item)}</span></td><td><div style={{ fontWeight: 700 }}>{label(item)}</div><div style={{ color: 'var(--text-muted)', fontSize: 12 }}>{item.memo || item.notes || ''}</div></td><td style={{ textTransform: 'capitalize' }}>{item.type || item.status || '—'}</td><td>{item.sourceName || item.fromAccountId || '—'}</td><td>{item.offsetName || item.toAccountId || item.category || '—'}</td><td style={{ textAlign: 'right', fontWeight: 800 }}>{item.currency || 'CAD'} ${money(item.amount)}</td></tr>)}{items.length === 0 && <tr><td colSpan={7} style={{ padding: 40, textAlign: 'center' }}>No transactions found.</td></tr>}</tbody></table></div>}<div style={{ display: 'flex', justifyContent: 'space-between', padding: 14, borderTop: '1px solid var(--border)' }}><span>Page {page} of {totalPages}</span><div style={{ display: 'flex', gap: 8 }}><button className="btn btn-secondary btn-sm" disabled={page <= 1 || loading} onClick={() => setPage(value => Math.max(1, value - 1))}>Previous</button><button className="btn btn-secondary btn-sm" disabled={page >= totalPages || loading} onClick={() => setPage(value => Math.min(totalPages, value + 1))}>Next</button></div></div></section>
  </div>{selected?.recordType === 'transactions' && <CloudPaymentDetailsModal payment={selected} onClose={() => setSelected(null)} onUpdated={updateSelected} />}{selected?.recordType === 'bills' && <CloudBillDetailsModal bill={{ ...selected, categoryName: selected.offsetName }} onClose={() => setSelected(null)} onUpdated={updateSelected} />}{selected?.recordType === 'accountTransfers' && <CloudTransferDetailsModal transfer={selected} onClose={() => setSelected(null)} onUpdated={updateSelected} />}</main>;
};
