import React, { useCallback, useEffect, useState } from 'react';
import { Check, Cloud, DollarSign, Download, Edit2, FolderDot, Globe, Layout, Link, Plus, Receipt, RefreshCw, ShieldCheck, Trash2, Users, X } from 'lucide-react';

type Settings = { isRtl: boolean; currency: 'CAD' | 'USD'; exchangeRate: number; donorSortBy: string; googleSheetSyncUrl: string };
type Project = { id: string; revision: number; name: string };
const defaults: Settings = { isRtl: false, currency: 'CAD', exchangeRate: 1.35, donorSortBy: 'lastName', googleSheetSyncUrl: '' };

export const OnlineSettings: React.FC = () => {
  const [settings,setSettings]=useState(defaults); const [revisions,setRevisions]=useState<Record<string,number>>({}); const [projects,setProjects]=useState<Project[]>([]); const [projectPage,setProjectPage]=useState(1); const [projectPages,setProjectPages]=useState(1); const [solaConfigured,setSolaConfigured]=useState(false); const [solaKeyInput,setSolaKeyInput]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [sheetUrl,setSheetUrl]=useState(''); const [newProject,setNewProject]=useState(''); const [editingProject,setEditingProject]=useState<Project|null>(null); const [downloading,setDownloading]=useState(false);
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const [settingsResponse,projectsResponse]=await Promise.all([fetch('/api/v3/settings'),fetch(`/api/v3/records/projects?page=${projectPage}&limit=50`)]);const [settingsData,projectsData]=await Promise.all([settingsResponse.json(),projectsResponse.json()]);if(!settingsResponse.ok||!settingsData.success)throw new Error(settingsData.error||'Unable to load settings.');if(!projectsResponse.ok||!projectsData.success)throw new Error(projectsData.error||'Unable to load projects.');setSettings(settingsData.settings);setSheetUrl(settingsData.settings.googleSheetSyncUrl||'');setRevisions(settingsData.revisions||{});setSolaConfigured(Boolean(settingsData.solaConfigured));setProjects(projectsData.items||[]);setProjectPages(Math.max(1,projectsData.totalPages||1));setError('');}catch(reason:any){if(!silent)setError(reason.message||'Unable to load settings.');}finally{if(!silent)setLoading(false);}},[projectPage]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),5000);return()=>window.clearInterval(timer);},[load]);
  const saveSetting=async(key:keyof Settings,value:any)=>{setSaving(key);setError('');setNotice('');const requestId=crypto.randomUUID();try{const response=await fetch(`/api/v3/settings/${key}`,{method:'PUT',headers:{'Content-Type':'application/json','Idempotency-Key':requestId},body:JSON.stringify({value,revision:revisions[key]})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to save setting.');setSettings(current=>({...current,[key]:data.value}));setRevisions(current=>({...current,[key]:data.revision}));if(key==='googleSheetSyncUrl')setSheetUrl(data.value);setNotice('Setting saved directly to the cloud.');}catch(reason:any){setError(reason.message||'Unable to save setting.');await load(true);}finally{setSaving('');}};
  const syncRate=async()=>{setSaving('exchangeRate');setError('');try{let response=await fetch('https://api.frankfurter.app/latest?base=USD&symbols=CAD');if(!response.ok)response=await fetch('https://open.er-api.com/v6/latest/USD');const data=await response.json();const rate=Number(data?.rates?.CAD);if(!Number.isFinite(rate)||rate<=0)throw new Error('No live rate was returned.');await saveSetting('exchangeRate',Number(rate.toFixed(4)));}catch(reason:any){setError(reason.message||'Unable to retrieve the live rate. Your saved rate was not changed.');setSaving('');}};
  const saveSolaKey=async()=>{const apiKey=solaKeyInput.trim();if(!apiKey)return;setSaving('sola');setError('');setNotice('');try{const response=await fetch('/api/v3/sola/configuration',{method:'PUT',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({apiKey})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to save the Sola key.');setSolaKeyInput('');setSolaConfigured(true);setNotice('Sola key saved securely on the server. It will never be displayed or downloaded.');}catch(reason:any){setError(reason.message||'Unable to save the Sola key.');}finally{setSaving('');}};
  const projectMutation=async(method:'POST'|'PUT'|'DELETE',item?:Project,name?:string)=>{const requestId=crypto.randomUUID();const response=await fetch(method==='POST'?'/api/v3/records/projects':`/api/v3/records/projects/${encodeURIComponent(item!.id)}`,{method,headers:{'Content-Type':'application/json','Idempotency-Key':requestId},body:JSON.stringify(method==='POST'?{data:{name}}:method==='PUT'?{revision:item!.revision,data:{name}}:{revision:item!.revision})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to save project.');await load(true);};
  const downloadBackup=async()=>{setDownloading(true);setError('');try{const records:any[]=[];let page=1,totalPages=1;do{const response=await fetch(`/api/v3/backup?page=${page}&limit=500`);const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to prepare backup.');records.push(...data.items);totalPages=Math.max(1,data.totalPages||1);page+=1;}while(page<=totalPages);const backup={format:'charitypro-cloud-backup',version:3,createdAt:new Date().toISOString(),recordCount:records.length,records,note:'Payment-gateway secrets are intentionally excluded.'};const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`charitypro_cloud_backup_${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setNotice(`Complete cloud backup prepared with ${records.length.toLocaleString()} records.`);}catch(reason:any){setError(reason.message||'Unable to download backup.');}finally{setDownloading(false);}};
  if(loading)return <div className="card" style={{margin:28,padding:44,textAlign:'center'}}>Loading online settings...</div>;
  return <main style={{padding:28,minHeight:'100vh',background:'var(--bg)'}}><div style={{maxWidth:1200,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:24}}>
    <div style={{gridColumn:'1 / -1'}}><div style={{color:'var(--green)',fontWeight:800,fontSize:13}}>CHARITYPRO CLOUD</div><h1 style={{margin:'4px 0',color:'var(--navy)'}}>Settings</h1><div style={{color:'var(--text-muted)'}}>Every saved preference is shared by both computers.</div></div>
    {error&&<div className="card" style={{gridColumn:'1 / -1',color:'var(--red)'}}>{error}</div>}{notice&&<div className="card" style={{gridColumn:'1 / -1',color:'var(--green)',fontWeight:700}}><Check size={16}/> {notice}</div>}
    <section className="card" style={{display:'grid',gap:26}}><h2 style={{margin:0,color:'var(--navy)'}}>System Preferences</h2>
      <Setting label="Language / Layout" icon={Layout}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><Choice active={!settings.isRtl} onClick={()=>void saveSetting('isRtl',false)}>🇨🇦 English / LTR</Choice><Choice active={settings.isRtl} onClick={()=>void saveSetting('isRtl',true)}>יידיש / RTL</Choice></div></Setting>
      <Setting label="Default Currency" icon={Globe}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>{(['CAD','USD'] as const).map(value=><Choice key={value} active={settings.currency===value} onClick={()=>void saveSetting('currency',value)}>{value} ($)</Choice>)}</div></Setting>
      <Setting label="Exchange Rate" icon={DollarSign}><div style={{display:'flex',gap:10}}><input type="number" min="0.0001" step="0.0001" value={settings.exchangeRate} onChange={event=>setSettings(current=>({...current,exchangeRate:Number(event.target.value)}))} onBlur={()=>void saveSetting('exchangeRate',settings.exchangeRate)}/><button className="btn btn-secondary" disabled={saving==='exchangeRate'} onClick={()=>void syncRate()}><RefreshCw size={16}/> Live Rate</button></div><small>1 USD = {settings.exchangeRate} CAD</small></Setting>
      <Setting label="Donor Sort Order" icon={Users}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>{[['lastName','English Last'],['firstName','English First'],['hebLastName','Yiddish Family'],['hebFirstName','Yiddish First']].map(([value,label])=><Choice key={value} active={settings.donorSortBy===value} onClick={()=>void saveSetting('donorSortBy',value)}>{label}</Choice>)}</div></Setting>
    </section>
    <section className="card" style={{display:'grid',gap:24}}><h2 style={{margin:0,color:'var(--navy)'}}>Receipts & System</h2><Setting label="Receipt Template" icon={Receipt}><div style={{border:'2px dashed var(--border)',borderRadius:12,padding:38,textAlign:'center',color:'var(--text-muted)'}}><Receipt size={38} style={{marginBottom:10}}/><div>Receipt design editor remains reserved for your existing template workflow.</div><button className="btn btn-secondary" style={{marginTop:12}} onClick={()=>alert('PDF receipt editor is coming soon.')}>Click to Edit</button></div></Setting><div style={{background:'var(--bg-input)',padding:16,borderRadius:12}}><h3 style={{margin:'0 0 8px',color:'var(--navy)'}}>Live Balance Calculation</h3><p style={{margin:'0 0 12px',color:'var(--text-muted)'}}>Bank, donor, payroll, and fundraiser balances are calculated from the complete online ledger every time. There is no local balance cache to repair.</p><div className="badge badge-green"><ShieldCheck size={14}/> Active</div></div><div style={{background:'var(--bg-input)',padding:16,borderRadius:12}}><strong>System Information</strong><Info label="Storage" value="Shared Cloud Database"/><Info label="Currency" value={settings.currency}/><Info label="Layout" value={settings.isRtl?'Right-to-Left':'Left-to-Right'}/><Info label="Data mode" value="Cloud Only"/></div></section>
    <section className="card" style={{gridColumn:'1 / -1',display:'grid',gap:18}}><h2 style={{margin:0,color:'var(--navy)'}}><Link size={20}/> Google Sheets Sync</h2><p style={{margin:0,color:'var(--text-muted)'}}>Paste the published CSV link used by the Donors page.</p><div style={{display:'flex',gap:10}}><input type="url" placeholder="https://docs.google.com/spreadsheets/..." value={sheetUrl} onChange={event=>setSheetUrl(event.target.value)}/>{settings.googleSheetSyncUrl&&<button className="btn btn-ghost" onClick={()=>void saveSetting('googleSheetSyncUrl','')}><X size={16}/></button>}<button className="btn btn-primary" disabled={!sheetUrl.trim()||saving==='googleSheetSyncUrl'} onClick={()=>void saveSetting('googleSheetSyncUrl',sheetUrl.trim())}>Save Link</button></div></section>
    <section className="card" style={{gridColumn:'1 / -1',display:'grid',gap:18}}><h2 style={{margin:0,color:'var(--navy)'}}><DollarSign size={20}/> Payment Gateway (Sola)</h2><p style={{margin:0,color:'var(--text-muted)'}}>Enter the production API key here just as before. It is sent once over the secure connection, stored only on the server, and is never returned to either browser or included in a backup.</p><div style={{padding:14,borderRadius:10,background:solaConfigured?'var(--green-bg)':'var(--yellow-bg)',color:solaConfigured?'var(--green)':'#9a6700',fontWeight:800}}>{solaConfigured?'✓ Sola key is securely configured on the server.':'Sola key is not configured on the server yet.'}</div><div style={{display:'flex',gap:10}}><input type="password" autoComplete="new-password" placeholder={solaConfigured?'Enter a replacement Sola production key':'Paste Sola production API key'} value={solaKeyInput} onChange={event=>setSolaKeyInput(event.target.value)} style={{flex:1,fontFamily:'monospace'}}/><button className="btn btn-primary" disabled={!solaKeyInput.trim()||saving==='sola'} onClick={()=>void saveSolaKey()}>{saving==='sola'?'Saving securely...':solaConfigured?'Replace Key':'Save Sola Key'}</button></div><small>The saved value is never shown again. To change it later, enter a replacement key.</small></section>
    <section className="card" style={{gridColumn:'1 / -1',display:'grid',gap:18}}><h2 style={{margin:0,color:'var(--navy)'}}><FolderDot size={20}/> Projects</h2><div style={{display:'flex',gap:10}}><input placeholder="New Project Name" value={newProject} onChange={event=>setNewProject(event.target.value)}/><button className="btn btn-primary" disabled={!newProject.trim()} onClick={async()=>{try{await projectMutation('POST',undefined,newProject.trim());setNewProject('');}catch(reason:any){setError(reason.message);}}}><Plus size={16}/> Add Project</button></div><div className="table-container"><table><thead><tr><th>Project Name</th><th>Actions</th></tr></thead><tbody>{projects.map(project=><tr key={project.id}><td>{editingProject?.id===project.id?<input value={editingProject.name} onChange={event=>setEditingProject({...editingProject,name:event.target.value})}/>:<strong>{project.name}</strong>}</td><td>{editingProject?.id===project.id?<><button className="btn btn-primary btn-sm" onClick={async()=>{try{await projectMutation('PUT',editingProject,editingProject.name.trim());setEditingProject(null);}catch(reason:any){setError(reason.message);}}}>Save</button><button className="btn btn-secondary btn-sm" onClick={()=>setEditingProject(null)}>Cancel</button></>:<><button className="btn btn-secondary btn-sm" onClick={()=>setEditingProject(project)}><Edit2 size={14}/></button><button className="btn btn-ghost btn-sm" style={{color:'var(--red)'}} onClick={async()=>{if(!confirm(`Delete project ${project.name}?`))return;try{await projectMutation('DELETE',project);}catch(reason:any){setError(reason.message);}}}><Trash2 size={14}/></button></>}</td></tr>)}{!projects.length&&<tr><td colSpan={2} style={{textAlign:'center',padding:20}}>No projects.</td></tr>}</tbody></table></div>{projectPages>1&&<div style={{display:'flex',justifyContent:'space-between'}}><button className="btn btn-secondary btn-sm" disabled={projectPage<=1} onClick={()=>setProjectPage(value=>value-1)}>Previous</button><span>Page {projectPage} of {projectPages} · 50 projects maximum</span><button className="btn btn-secondary btn-sm" disabled={projectPage>=projectPages} onClick={()=>setProjectPage(value=>value+1)}>Next</button></div>}</section>
    <section className="card" style={{gridColumn:'1 / -1',display:'flex',alignItems:'center',gap:20}}><Cloud size={34} color="var(--blue)"/><div style={{flex:1}}><h2 style={{margin:'0 0 6px',color:'var(--navy)'}}>Complete Cloud Backup</h2><p style={{margin:0,color:'var(--text-muted)'}}>Downloads every current online record in safe batches. It does not use or depend on this computer’s local storage.</p></div><button className="btn btn-primary" disabled={downloading} onClick={()=>void downloadBackup()}><Download size={16}/>{downloading?'Preparing...':'Download Backup'}</button></section>
  </div></main>;
};

const Setting:React.FC<{label:string;icon:React.ElementType;children:React.ReactNode}>=({label,icon:Icon,children})=><div><div style={{display:'flex',alignItems:'center',gap:8,fontWeight:800,color:'var(--text-secondary)',marginBottom:11,textTransform:'uppercase',fontSize:13}}><Icon size={16}/>{label}</div>{children}</div>;
const Choice:React.FC<{active:boolean;onClick:()=>void;children:React.ReactNode}>=({active,onClick,children})=><button onClick={onClick} style={{padding:13,borderRadius:10,border:`2px solid ${active?'var(--navy-light)':'var(--border)'}`,background:active?'var(--navy-bg)':'var(--bg-input)',color:active?'var(--navy-light)':'var(--text-muted)',fontWeight:800,cursor:'pointer'}}>{children}{active?' ✓':''}</button>;
const Info:React.FC<{label:string;value:string}>=({label,value})=><div style={{display:'flex',justifyContent:'space-between',padding:'8px 0',borderBottom:'1px solid var(--border-light)'}}><span style={{color:'var(--text-muted)'}}>{label}</span><strong>{value}</strong></div>;
