import React, { useCallback, useEffect, useRef, useState } from 'react';
import Papa from 'papaparse';
import { get } from 'idb-keyval';
import { CloudBillDetailsModal } from '../components/CloudBillDetailsModal';
import { CloudTransactionModal } from '../components/CloudTransactionModal';
import { CloudAccountDetailsModal } from '../components/CloudAccountDetailsModal';

type Tab = 'bills' | 'categories' | 'queue';
type Bill = { id: string; revision: number; vendor: string; amount: number; currency?: 'CAD' | 'USD'; dueDate: string; status: string; category: string; categoryName: string; sourceName?: string; sourceAccountId?: string; memo?: string; taxable?: boolean; exchangeRate?: number };
type Account = { id: string; revision?: number; name: string; type: string; currency: string; parentId?: string; balance?: number };
type Category = Account & { revision: number; ytd: number };
type QueueItem = { id: string; revision: number; date: string; description: string; amount: number; taxable?: boolean };

export const OnlineExpenses: React.FC = () => {
  const [tab,setTab]=useState<Tab>('bills'); const [items,setItems]=useState<Bill[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [queue,setQueue]=useState<QueueItem[]>([]);
  const [page,setPage]=useState(1); const [total,setTotal]=useState(0); const [totalPages,setTotalPages]=useState(1); const [totalCAD,setTotalCAD]=useState(0); const [totalYTD,setTotalYTD]=useState(0);
  const [status,setStatus]=useState('all'); const [category,setCategory]=useState(''); const [account,setAccount]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [searchInput,setSearchInput]=useState(''); const [search,setSearch]=useState('');
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [showAdd,setShowAdd]=useState(false); const [selectedBill,setSelectedBill]=useState<Bill|null>(null); const [paying,setPaying]=useState<Bill|null>(null); const [paySource,setPaySource]=useState(''); const [saving,setSaving]=useState(false); const [processing,setProcessing]=useState<QueueItem|null>(null); const [selectedCategory,setSelectedCategory]=useState<Category|null>(null); const [showCategory,setShowCategory]=useState(false); const [categoryName,setCategoryName]=useState(''); const [parentId,setParentId]=useState('');
  const payRequestIds=useRef<Record<string,string>>({}); const fileInput=useRef<HTMLInputElement|null>(null);

  useEffect(()=>{const timer=window.setTimeout(()=>{setSearch(searchInput.trim());setPage(1);},220);return()=>window.clearTimeout(timer);},[searchInput]);
  useEffect(()=>{fetch('/api/v3/accounts?limit=100').then(r=>r.json()).then(data=>{if(data.success)setAccounts(data.items);}).catch(()=>undefined);},[]);

  const load=useCallback(async(silent=false)=>{if(!silent){setLoading(true);setError('');}try{
    if(tab==='bills'){const params=new URLSearchParams({page:String(page),limit:'50',status});if(search)params.set('search',search);if(category)params.set('category',category);if(account)params.set('account',account);if(from)params.set('from',from);if(to)params.set('to',to);const response=await fetch(`/api/v3/bills?${params}`);const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to load expenses.');setItems(data.items);setTotal(data.total);setTotalPages(Math.max(1,data.totalPages));setTotalCAD(Number(data.totalCAD||0));}
    else if(tab==='categories'){const response=await fetch(`/api/v3/expense-categories?page=${page}&limit=50&search=${encodeURIComponent(search)}`);const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to load expense categories.');setCategories(data.items);setTotal(data.total);setTotalPages(Math.max(1,data.totalPages));setTotalYTD(Number(data.totalYTD||0));}
    else {const response=await fetch(`/api/v3/records/expenseQueueItems?page=${page}&limit=50&search=${encodeURIComponent(search)}`);const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to load the processing queue.');setQueue(data.items);setTotal(data.total);setTotalPages(Math.max(1,data.totalPages));}
  }catch(reason:any){if(!silent)setError(reason.message||'Unable to load expenses.');}finally{if(!silent)setLoading(false);}},[tab,page,status,category,account,from,to,search]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),3000);return()=>window.clearInterval(timer);},[load]);
  const changeTab=(value:Tab)=>{setTab(value);setPage(1);setSearchInput('');setSearch('');setError('');setNotice('');};

  useEffect(()=>{let active=true;(async()=>{try{const raw:any=await get('charity-store');const saved=typeof raw==='string'?JSON.parse(raw):raw;const oldQueue=saved?.state?.uploadedExpenseQueue;if(!Array.isArray(oldQueue)||!oldQueue.length)return;let rescued=0;for(const item of oldQueue){if(!item?.id||!item?.date||!item?.description||!(Number(item.amount)>0))continue;const response=await fetch('/api/v3/records/expenseQueueItems',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':`legacy-expense-queue-${item.id}`},body:JSON.stringify({data:{id:String(item.id),date:String(item.date).slice(0,10),description:String(item.description),amount:Math.abs(Number(item.amount)),taxable:Boolean(item.taxable)}})});if(response.ok)rescued++;}if(active&&rescued){setNotice(`${rescued} waiting expense${rescued===1?' was':'s were'} recovered from this computer and saved online.`);void load(true);}}catch{/* Old local storage may not exist on this computer. */}})();return()=>{active=false;};},[]);

  const markPaid=async()=>{if(!paying||!paySource)return;setSaving(true);setError('');const key=payRequestIds.current[paying.id]||crypto.randomUUID();payRequestIds.current[paying.id]=key;try{const response=await fetch(`/api/v3/bills/${encodeURIComponent(paying.id)}/pay`,{method:'PATCH',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({requestId:key,revision:paying.revision,sourceAccountId:paySource})});const data=await response.json();if(!response.ok||!data.success){delete payRequestIds.current[paying.id];throw new Error(data.error||'Expense could not be marked paid.');}delete payRequestIds.current[paying.id];setPaying(null);setPaySource('');setNotice('Expense marked paid. Account balances were recalculated online.');void load();}catch(reason:any){setError(reason.message||'Expense could not be marked paid.');}finally{setSaving(false);}};
  const removeQueue=async(item:QueueItem,confirm=true)=>{if(confirm&&!window.confirm(`Remove ${item.description} from the processing queue?`))return false;const key=crypto.randomUUID();const response=await fetch(`/api/v3/records/expenseQueueItems/${encodeURIComponent(item.id)}`,{method:'DELETE',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({revision:item.revision})});const data=await response.json();if(!response.ok||!data.success){setError(data.error||'Unable to remove the queue item.');return false;}await load(true);return true;};
  const importCsv=(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;Papa.parse(file,{header:true,skipEmptyLines:true,complete:async results=>{const rows=results.data as any[];let imported=0;for(const row of rows){const keys=Object.keys(row);const dateKey=keys.find(key=>key.toLowerCase().includes('date'))||keys[0];const descriptionKey=keys.find(key=>/desc|name|payee|vendor/i.test(key))||keys[1];const amountKey=keys.find(key=>/amount|total/i.test(key))||keys[2];const amount=Math.abs(Number.parseFloat(String(row[amountKey]||'').replace(/[^0-9.-]+/g,'')));if(!row[dateKey]||!Number.isFinite(amount)||amount<=0)continue;const parsedDate=new Date(row[dateKey]);const data={id:crypto.randomUUID(),date:Number.isNaN(parsedDate.getTime())?new Date().toISOString().slice(0,10):parsedDate.toISOString().slice(0,10),description:String(row[descriptionKey]||'Imported Expense').trim(),amount,taxable:false};const key=crypto.randomUUID();const response=await fetch('/api/v3/records/expenseQueueItems',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({data})});if(response.ok)imported++;}setTab('queue');setPage(1);setNotice(`${imported} expense${imported===1?'':'s'} uploaded into the shared processing queue.`);void load();}});event.target.value='';};
  const addCategory=async()=>{if(!categoryName.trim())return;setSaving(true);const key=crypto.randomUUID();try{const response=await fetch('/api/v3/records/accounts',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({data:{name:categoryName.trim(),type:'expense',currency:'CAD',startingBalance:0,...(parentId?{parentId}:{})}})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to add category.');setShowCategory(false);setCategoryName('');setParentId('');setNotice('Expense category saved online.');const accountData=await fetch('/api/v3/accounts?limit=100').then(r=>r.json());if(accountData.success)setAccounts(accountData.items);void load();}catch(reason:any){setError(reason.message||'Unable to add category.');}finally{setSaving(false);}};
  const expenseAccounts=accounts.filter(item=>item.type==='expense');const paymentAccounts=accounts.filter(item=>item.type==='asset'||item.type==='liability');

  return <main style={{minHeight:'100vh',background:'var(--bg)',padding:28,fontFamily:'Inter, sans-serif'}}><div style={{maxWidth:1400,margin:'0 auto'}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',marginBottom:18}}><div><div style={{color:'var(--green)',fontWeight:800,fontSize:13}}>CHARITYPRO CLOUD</div><h1 style={{color:'var(--navy)',margin:'4px 0'}}>Expenses {tab==='bills'&&`(${total.toLocaleString()})`}</h1><div style={{color:'var(--text-muted)',fontSize:13}}>Shared online records · live filters · 50 records per page</div></div>{tab==='bills'&&<button className="btn btn-primary" onClick={()=>{setShowAdd(true);setNotice('');}}>+ Add Bill</button>}{tab==='categories'&&<button className="btn btn-primary" onClick={()=>setShowCategory(true)}>+ Add Category</button>}{tab==='queue'&&<button className="btn btn-primary" onClick={()=>fileInput.current?.click()}>Upload Expense Sheet</button>}<input ref={fileInput} type="file" accept=".csv" style={{display:'none'}} onChange={importCsv}/></div>
    <div style={{display:'flex',gap:8,marginBottom:18,borderBottom:'2px solid var(--border)',paddingBottom:12}}><button className={`btn ${tab==='bills'?'btn-primary':'btn-ghost'}`} onClick={()=>changeTab('bills')}>Bills & Expenses</button><button className={`btn ${tab==='categories'?'btn-primary':'btn-ghost'}`} onClick={()=>changeTab('categories')}>Expense Categories</button><button className={`btn ${tab==='queue'?'btn-primary':'btn-ghost'}`} onClick={()=>changeTab('queue')}>Processing Queue {queue.length>0&&<span className="badge badge-red" style={{marginLeft:6}}>{queue.length}</span>}</button></div>
    {showAdd&&<CloudTransactionModal mode="add" onClose={()=>setShowAdd(false)} onSaved={message=>{setShowAdd(false);setNotice(message);setPage(1);void load();}}/>}
    {processing&&<CloudTransactionModal mode="add" initialData={{id:processing.id,revision:processing.revision,vendor:processing.description,amount:processing.amount,dueDate:processing.date,taxable:processing.taxable}} onClose={()=>setProcessing(null)} onSaved={message=>{const item=processing;setProcessing(null);setNotice(`${message} The processed queue item was removed.`);if(item)void removeQueue(item,false);}}/>}
    {paying&&<div className="modal-overlay" onClick={()=>setPaying(null)}><section className="modal" onClick={event=>event.stopPropagation()} style={{maxWidth:560}}><div className="modal-header"><h2 style={{margin:0}}>Mark {paying.vendor} Paid</h2><button className="modal-close" onClick={()=>setPaying(null)}>×</button></div><div className="modal-body"><p>{paying.currency||'CAD'} ${paying.amount.toFixed(2)} allocated to {paying.categoryName}</p><label className="form-group"><span>Paid from *</span><select value={paySource} onChange={event=>setPaySource(event.target.value)}><option value="">Select asset or liability account</option>{paymentAccounts.map(item=><option key={item.id} value={item.id}>{item.name} ({item.currency})</option>)}</select></label></div><div className="modal-footer"><button className="btn btn-secondary" onClick={()=>setPaying(null)}>Cancel</button><button className="btn btn-primary" disabled={!paySource||saving} onClick={()=>void markPaid()}>{saving?'Saving securely...':'Confirm Paid'}</button></div></section></div>}
    {showCategory&&<div className="modal-overlay" onClick={()=>setShowCategory(false)}><section className="modal" onClick={event=>event.stopPropagation()} style={{maxWidth:520}}><div className="modal-header"><h2 style={{margin:0}}>Add Expense Category</h2><button className="modal-close" onClick={()=>setShowCategory(false)}>×</button></div><div className="modal-body"><label className="form-group"><span>Category name *</span><input autoFocus value={categoryName} onChange={event=>setCategoryName(event.target.value)}/></label><label className="form-group"><span>Parent category (optional)</span><select value={parentId} onChange={event=>setParentId(event.target.value)}><option value="">Top-level category</option>{expenseAccounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="modal-footer"><button className="btn btn-secondary" onClick={()=>setShowCategory(false)}>Cancel</button><button className="btn btn-primary" disabled={!categoryName.trim()||saving} onClick={()=>void addCategory()}>{saving?'Saving...':'Add Category'}</button></div></section></div>}
    {notice&&<div className="card" style={{padding:14,color:'var(--green)',fontWeight:800,marginBottom:16}}>{notice}</div>}{error&&<div className="card" style={{padding:14,color:'var(--red)',fontWeight:700,marginBottom:16}}>{error}</div>}
    <section className="card" style={{padding:16,marginBottom:18}}><div style={{display:'grid',gridTemplateColumns:tab==='bills'?'minmax(220px,1fr) 150px 170px 170px 145px 145px':'1fr',gap:10}}><input value={searchInput} onChange={event=>setSearchInput(event.target.value)} placeholder={tab==='bills'?'Live search: vendor, memo, category, account, status, date or amount':tab==='categories'?'Live search categories':'Live search queue description, date or amount'}/>{tab==='bills'&&<><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="all">All expenses</option><option value="open">Open expenses</option><option value="paid">Paid expenses</option><option value="urgent">Urgent</option><option value="pending">Pending</option><option value="scheduled">Scheduled</option></select><select value={category} onChange={event=>{setCategory(event.target.value);setPage(1);}}><option value="">All categories</option>{expenseAccounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={account} onChange={event=>{setAccount(event.target.value);setPage(1);}}><option value="">All paid-from accounts</option>{paymentAccounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="date" value={from} onChange={event=>{setFrom(event.target.value);setPage(1);}} title="From due date"/><input type="date" value={to} onChange={event=>{setTo(event.target.value);setPage(1);}} title="To due date"/></>}</div></section>
    {tab==='bills'&&<div style={{color:'var(--green)',fontWeight:800,margin:'-8px 0 14px'}}>Filtered total: ${totalCAD.toLocaleString('en-CA',{minimumFractionDigits:2,maximumFractionDigits:2})} CAD</div>}{tab==='categories'&&<div style={{color:'var(--navy)',fontWeight:800,margin:'-8px 0 14px'}}>Total year-to-date expenses: ${totalYTD.toLocaleString('en-CA',{minimumFractionDigits:2,maximumFractionDigits:2})} CAD</div>}
    <section className="card" style={{padding:0,overflow:'hidden'}}>{loading?<div style={{padding:40,textAlign:'center'}}>Loading 50 records from the cloud...</div>:tab==='bills'?<BillTable items={items} onSelect={setSelectedBill} onPay={bill=>{setPaying(bill);setPaySource('');}}/>:tab==='categories'?<CategoryTable items={categories} total={totalYTD} onSelect={setSelectedCategory}/>:<QueueTable items={queue} onProcess={setProcessing} onRemove={item=>void removeQueue(item)}/>}<div style={{display:'flex',justifyContent:'space-between',padding:14,borderTop:'1px solid var(--border)'}}><span>Page {page} of {totalPages} · {total.toLocaleString()} records</span><div style={{display:'flex',gap:8}}><button className="btn btn-secondary btn-sm" disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)}>Previous</button><button className="btn btn-secondary btn-sm" disabled={page>=totalPages||loading} onClick={()=>setPage(value=>value+1)}>Next</button></div></div></section>
    {selectedBill&&<CloudBillDetailsModal bill={selectedBill} onClose={()=>setSelectedBill(null)} onUpdated={bill=>{setSelectedBill(bill);void load(true);}} onMarkPaid={bill=>{setSelectedBill(null);setPaying(bill);setPaySource('');}}/>}{selectedCategory&&<CloudAccountDetailsModal account={{...selectedCategory,balance:selectedCategory.ytd}} onClose={()=>setSelectedCategory(null)} onUpdated={account=>{setSelectedCategory(current=>current?{...current,...account,ytd:current.ytd}:current);void load(true);}}/>}
  </div></main>;
};

const BillTable:React.FC<{items:Bill[];onSelect:(item:Bill)=>void;onPay:(item:Bill)=>void}>=({items,onSelect,onPay})=><div style={{overflowX:'auto'}}><table><thead><tr><th>Due date</th><th>Vendor / description</th><th>Category</th><th>Status</th><th>Paid from</th><th style={{textAlign:'right'}}>Amount</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>onSelect(item)} style={{cursor:'pointer'}}><td>{item.dueDate}</td><td><strong>{item.vendor}</strong><div style={{color:'var(--text-muted)',fontSize:12}}>{item.memo||''}</div></td><td>{item.categoryName}</td><td>{item.status}</td><td>{item.sourceName||''}</td><td style={{textAlign:'right',fontWeight:800}}>{item.currency||'CAD'} ${item.amount.toFixed(2)}</td><td>{item.status!=='paid'&&<button className="btn btn-primary btn-sm" onClick={event=>{event.stopPropagation();onPay(item);}}>Mark Paid</button>}</td></tr>)}{!items.length&&<tr><td colSpan={7} style={{padding:30,textAlign:'center'}}>No matching expenses.</td></tr>}</tbody></table></div>;
const CategoryTable:React.FC<{items:Category[];total:number;onSelect:(item:Category)=>void}>=({items,total,onSelect})=><div style={{overflowX:'auto'}}><table><thead><tr><th>Category</th><th>Parent</th><th style={{textAlign:'right'}}>YTD spent</th><th>% of total</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>onSelect(item)} style={{cursor:'pointer'}}><td><strong>{item.name}</strong></td><td>{items.find(parent=>parent.id===item.parentId)?.name||'—'}</td><td style={{textAlign:'right',fontWeight:800}}>${item.ytd.toFixed(2)}</td><td>{total?`${(item.ytd/total*100).toFixed(1)}%`:'0%'}</td></tr>)}{!items.length&&<tr><td colSpan={4} style={{padding:30,textAlign:'center'}}>No matching expense categories.</td></tr>}</tbody></table></div>;
const QueueTable:React.FC<{items:QueueItem[];onProcess:(item:QueueItem)=>void;onRemove:(item:QueueItem)=>void}>=({items,onProcess,onRemove})=><div style={{overflowX:'auto'}}><table><thead><tr><th>Date</th><th>Description</th><th>Taxable</th><th style={{textAlign:'right'}}>Amount</th><th>Action</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.date}</td><td><strong>{item.description}</strong></td><td>{item.taxable?'Yes':'No'}</td><td style={{textAlign:'right',fontWeight:800}}>${item.amount.toFixed(2)}</td><td><button className="btn btn-primary btn-sm" onClick={()=>onProcess(item)}>Process / Match</button> <button className="btn btn-ghost btn-sm" onClick={()=>onRemove(item)}>Remove</button></td></tr>)}{!items.length&&<tr><td colSpan={5} style={{padding:30,textAlign:'center'}}>Queue is empty. Upload a CSV expense sheet to add records for processing.</td></tr>}</tbody></table></div>;
