import React, { useCallback, useEffect, useState } from 'react';
import { Edit2, X } from 'lucide-react';
import { CloudPaymentDetailsModal } from './CloudPaymentDetailsModal';
import { CloudAccountEditModal } from './CloudAccountEditModal';
import { CloudBillDetailsModal } from './CloudBillDetailsModal';
import { CloudTransferDetailsModal } from './CloudTransferDetailsModal';

type Account = { id: string; name: string; type: string; currency: string; balance: number; revision: number; subType?: string; startingBalance?: number };
type Entry = { id: string; recordType: string; [key: string]: any };

export const CloudAccountDetailsModal: React.FC<{ account: Account; onClose: () => void; onUpdated?: (account: Account) => void }> = ({ account, onClose, onUpdated }) => {
  const [currentAccount, setCurrentAccount] = useState(account); const [editingAccount, setEditingAccount] = useState(false);
  const [items, setItems] = useState<Entry[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<Entry | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch(`/api/v3/accounts/${encodeURIComponent(currentAccount.id)}/ledger?page=${page}&limit=50`); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Unable to load account details.'); setItems(data.items); setTotal(Number(data.total || 0)); setTotalPages(Math.max(1, Number(data.totalPages || 1))); } catch (e: any) { setError(e.message || 'Unable to load account details.'); } finally { setLoading(false); } }, [currentAccount.id, page]);
  useEffect(() => { void load(); }, [load]);
  const rows = items.map(item => describe(item, currentAccount));
  return <><div className="modal-overlay" onClick={onClose}><div className="modal" onClick={event => event.stopPropagation()} style={{ maxWidth: 950, width: '94%', maxHeight: '90vh', overflowY: 'auto' }}>
    <div className="modal-header"><div><h2 style={{ margin: 0 }}>{currentAccount.name}</h2><div style={{ color: 'var(--text-muted)', fontSize: 13, textTransform: 'capitalize' }}>{currentAccount.type} · {currentAccount.currency}</div></div><button className="modal-close" onClick={onClose}><X size={20} /></button></div>
    <div className="modal-body"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'end', paddingBottom: 18, marginBottom: 18, borderBottom: '1px solid var(--border)' }}><div><div style={{ color: 'var(--text-muted)', fontSize: 12, textTransform: 'uppercase' }}>Cloud-calculated balance</div><div style={{ fontSize: 30, fontWeight: 900, color: currentAccount.balance >= 0 ? 'var(--green)' : 'var(--red)' }}>{currentAccount.currency} ${currentAccount.balance.toLocaleString('en-CA', { minimumFractionDigits: 2 })}</div></div><div style={{ color: 'var(--text-muted)' }}>{total.toLocaleString()} ledger entries</div></div>{error && <div style={{ color: 'var(--red)', fontWeight: 700, marginBottom: 14 }}>{error}</div>}{loading ? <div style={{ padding: 40, textAlign: 'center' }}>Loading 50 account entries...</div> : <div className="table-container"><table><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Side</th><th style={{ textAlign: 'right' }}>Amount</th><th style={{ textAlign: 'right' }}>Balance Impact</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.item.recordType}-${row.item.id}`} onClick={() => setSelected(row.item)} style={{ cursor: 'pointer' }}><td>{row.date}</td><td style={{ textTransform: 'capitalize' }}>{row.item.recordType === 'accountTransfers' ? 'Transfer' : row.item.recordType === 'bills' ? 'Bill' : 'Payment'}</td><td>{row.description}</td><td>{row.isCredit ? 'Credit' : 'Debit'}</td><td style={{ textAlign: 'right', fontWeight: 700 }}>{currentAccount.currency} ${Number(row.amount).toFixed(2)}</td><td style={{ textAlign: 'right', fontWeight: 800, color: row.impact >= 0 ? 'var(--green)' : 'var(--red)' }}>{row.impact >= 0 ? '+' : '-'}${Math.abs(row.impact).toFixed(2)}</td></tr>)}{rows.length === 0 && <tr><td colSpan={6} style={{ padding: 30, textAlign: 'center' }}>No ledger entries for this account.</td></tr>}</tbody></table></div>}<div style={{ display: 'flex', justifyContent: 'space-between', paddingTop: 16 }}><span>Page {page} of {totalPages} · 50 maximum</span><div style={{ display: 'flex', gap: 8 }}><button className="btn btn-secondary btn-sm" disabled={page <= 1 || loading} onClick={() => setPage(value => Math.max(1, value - 1))}>Previous</button><button className="btn btn-secondary btn-sm" disabled={page >= totalPages || loading} onClick={() => setPage(value => Math.min(totalPages, value + 1))}>Next</button></div></div></div>
    <div className="modal-footer"><button className="btn btn-secondary" onClick={onClose}>Close</button><button className="btn btn-primary" onClick={() => setEditingAccount(true)}><Edit2 size={15} /> Edit All Details</button></div>
  </div></div>{selected?.recordType === 'transactions' && <CloudPaymentDetailsModal payment={{ ...selected, donorName: selected.donorName || selected.notes || 'Donation / Income' }} onClose={() => setSelected(null)} onUpdated={payment => { setSelected({ ...payment, recordType: 'transactions' }); void load(); }} />}{selected?.recordType === 'bills' && <CloudBillDetailsModal bill={selected} onClose={() => setSelected(null)} onUpdated={bill => { setSelected({ ...bill, recordType: 'bills' }); void load(); }} />}{selected?.recordType === 'accountTransfers' && <CloudTransferDetailsModal transfer={selected} onClose={() => setSelected(null)} onUpdated={transfer => { setSelected({ ...transfer, recordType: 'accountTransfers' }); void load(); }} />}{editingAccount && <CloudAccountEditModal account={currentAccount} onClose={() => setEditingAccount(false)} onSaved={updated => { setEditingAccount(false); setCurrentAccount(updated); onUpdated?.(updated); }} />}</>;
};

const describe = (item: Entry, account: Account) => { let date = item.date || item.paidDate || item.dueDate || ''; let description = ''; let isCredit = false; const amount = Number(item.amount || 0); if (item.recordType === 'transactions') { description = item.notes || 'Donation / Income'; isCredit = item.offsetAccountId === account.id; } else if (item.recordType === 'bills') { description = `${item.vendor || 'Bill'}${item.memo ? ` — ${item.memo}` : ''}`; isCredit = item.sourceAccountId === account.id; } else { const outgoing = item.fromAccountId === account.id; description = outgoing ? `Internal Transfer to ${item.toAccountId}` : `Internal Transfer from ${item.fromAccountId}`; isCredit = outgoing; } const normalDebit = account.type === 'asset' || account.type === 'expense'; const impact = (normalDebit ? !isCredit : isCredit) ? amount : -amount; return { item, date, description, isCredit, amount, impact }; };
