import React, { useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';

type Donor = { id: string; name: string };
export const CloudPledgeEditModal: React.FC<{ pledge: any; onClose: () => void; onSaved: (pledge: any) => void }> = ({ pledge, onClose, onSaved }) => {
  const [form, setForm] = useState({ donorId: pledge.donorId || '', amount: String(pledge.amount || ''), currency: pledge.currency || 'CAD', date: pledge.date || '', category: pledge.category || '', sponsor: pledge.sponsor || '', notes: pledge.notes || '' }); const [donorSearch, setDonorSearch] = useState(pledge.donorName || ''); const [donors, setDonors] = useState<Donor[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const requestId = useRef('');
  useEffect(() => { const timer = window.setTimeout(() => { fetch(`/api/v3/donors?limit=50&search=${encodeURIComponent(donorSearch)}`).then(response => response.json()).then(data => { if (data.success) setDonors(data.items); }).catch(() => undefined); }, 200); return () => window.clearTimeout(timer); }, [donorSearch]);
  const set = (field: string, value: string) => setForm(current => ({ ...current, [field]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); const amount = Number(form.amount); if (!form.donorId || !Number.isFinite(amount) || amount <= 0 || !form.date) { setError('Donor, positive amount, and date are required.'); return; } setSaving(true); setError(''); const key = requestId.current || crypto.randomUUID(); requestId.current = key; try { const response = await fetch(`/api/v3/records/pledges/${encodeURIComponent(pledge.id)}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify({ revision: pledge.revision, data: { ...form, amount } }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Unable to save pledge.'); requestId.current = ''; onSaved({ ...pledge, ...data.item, donorName: donors.find(donor => donor.id === data.item.donorId)?.name || pledge.donorName }); } catch (reason: any) { requestId.current = ''; setError(reason.message || 'Unable to save pledge.'); } finally { setSaving(false); } };
  return <div className="modal-overlay" onClick={onClose}><form className="modal" onSubmit={save} onClick={event => event.stopPropagation()} style={{ maxWidth: 720, width: '92%' }}><div className="modal-header"><h2 style={{ margin: 0 }}>Edit Pledge</h2><button type="button" className="modal-close" onClick={onClose}><X size={20} /></button></div><div className="modal-body">{error && <div style={{ color: 'var(--red)', fontWeight: 700, marginBottom: 14 }}>{error}</div>}<div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 14 }}><label className="form-group" style={{ margin: 0 }}><span>Find Donor</span><input value={donorSearch} onChange={event => setDonorSearch(event.target.value)} /></label><label className="form-group" style={{ margin: 0 }}><span>Donor *</span><select value={form.donorId} onChange={event => set('donorId', event.target.value)}><option value="">Select donor</option>{!donors.some(donor => donor.id === form.donorId) && <option value={pledge.donorId}>{pledge.donorName}</option>}{donors.map(donor => <option key={donor.id} value={donor.id}>{donor.name}</option>)}</select></label><label className="form-group" style={{ margin: 0 }}><span>Amount *</span><input type="number" min="0.01" step="0.01" value={form.amount} onChange={event => set('amount', event.target.value)} /></label><label className="form-group" style={{ margin: 0 }}><span>Currency</span><select value={form.currency} onChange={event => set('currency', event.target.value)}><option>CAD</option><option>USD</option></select></label><label className="form-group" style={{ margin: 0 }}><span>Date *</span><input type="date" value={form.date} onChange={event => set('date', event.target.value)} /></label><label className="form-group" style={{ margin: 0 }}><span>Category</span><input value={form.category} onChange={event => set('category', event.target.value)} /></label><label className="form-group" style={{ margin: 0 }}><span>Sponsor</span><input value={form.sponsor} onChange={event => set('sponsor', event.target.value)} /></label><label className="form-group" style={{ margin: 0, gridColumn: '1 / -1' }}><span>Notes</span><textarea rows={4} value={form.notes} onChange={event => set('notes', event.target.value)} /></label></div></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving...' : 'Save All Changes'}</button></div></form></div>;
};
