import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Edit2, X } from 'lucide-react';
import type { OnlineDonor } from './OnlineDonorForm';
import { CloudPaymentDetailsModal } from './CloudPaymentDetailsModal';
import { CloudPledgeDetailsModal } from './CloudPledgeDetailsModal';
import { CloudScheduleDetailsModal } from './CloudScheduleDetailsModal';
import { OnlinePaymentForm } from './OnlinePaymentForm';
import { CloudRecurringPaymentForm } from './CloudRecurringPaymentForm';

type Profile = { donor: OnlineDonor & Record<string, any>; payments: any[]; pledges: any[]; recurring: any[]; summary: Record<string, number> };
type Tab = 'overview' | 'transactions' | 'pledges' | 'recurring' | 'declined' | 'notes';
const money = (value: number) => Number(value || 0).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export const CloudDonorProfileModal: React.FC<{ donorId: string; onClose: () => void; onEdit: (donor: OnlineDonor) => void }> = ({ donorId, onClose, onEdit }) => {
  const [profile, setProfile] = useState<Profile | null>(null); const [tab, setTab] = useState<Tab>('overview');
  const [error, setError] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false);
  const [selectedPayment, setSelectedPayment] = useState<any | null>(null); const [selectedPledgeId, setSelectedPledgeId] = useState<string | null>(null);
  const [selectedSchedule, setSelectedSchedule] = useState<any | null>(null);
  const [showPayment, setShowPayment] = useState(false); const [showRecurring, setShowRecurring] = useState(false); const [notice, setNotice] = useState('');
  const requestId = useRef('');
  const loadProfile = useCallback(async (signal?: AbortSignal) => { try { const response = await fetch(`/api/v3/donors/${encodeURIComponent(donorId)}/profile`, { signal }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Unable to load donor profile.'); setProfile(data); setNotes(data.donor.notes || ''); setError(''); } catch (e: any) { if (e.name !== 'AbortError') setError(e.message || 'Unable to load donor profile.'); } }, [donorId]);
  useEffect(() => { const controller = new AbortController(); void loadProfile(controller.signal); return () => controller.abort(); }, [loadProfile]);
  const saveNotes = async () => { if (!profile) return; setSaving(true); const key = requestId.current || crypto.randomUUID(); requestId.current = key; try { const response = await fetch(`/api/v3/donors/${encodeURIComponent(profile.donor.id)}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify({ requestId: key, revision: profile.donor.revision, notes }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Unable to save notes.'); requestId.current = ''; setProfile(current => current ? { ...current, donor: { ...current.donor, ...data.item } } : current); } catch (e: any) { requestId.current = ''; setError(e.message || 'Unable to save notes.'); } finally { setSaving(false); } };
  const statusBadge = (type: string) => <span className={`badge ${type === 'approved' ? 'badge-green' : type === 'pending' ? 'badge-yellow' : type === 'declined' ? 'badge-red' : 'badge-gray'}`}>{type}</span>;
  const donor = profile?.donor; const summary = profile?.summary || {}; const declined = profile?.payments.filter(payment => payment.type === 'declined') || [];
  const initials = donor ? `${String(donor.firstName || donor.name || '?')[0]}${String(donor.lastName || '')[0] || ''}` : '';
  const hebrewName = donor ? [donor.preTitle, donor.hebFirstName, donor.hebLastName, donor.title, donor.postTitle].filter(Boolean).join(' ') : '';
  const tabs: [Tab, string][] = [['overview','Overview'],['transactions',`Payments (${summary.paymentCount || 0})`],['pledges',`Pledges (${summary.pledgeCount || 0})`],['recurring',`Recurring (${summary.recurringCount || 0})`],['declined',`Declined (${summary.declinedCount || 0})`],['notes','Notes']];

  return <><div className="modal-overlay" onClick={onClose}><div className="modal" onClick={event => event.stopPropagation()} style={{ maxWidth: 900, width: '90%', maxHeight: '90vh', overflowY: 'auto' }}>
    <div className="modal-header"><h2 style={{ margin: 0 }}>Donor Profile</h2><button className="modal-close" onClick={onClose}><X size={20} /></button></div>
    <div className="modal-body">{error && <div style={{ color: 'var(--red)', fontWeight: 700, marginBottom: 14 }}>{error}</div>}{notice && <div style={{ color: 'var(--green)', fontWeight: 800, marginBottom: 14 }}>{notice}</div>}{!profile && !error && <div style={{ padding: 40, textAlign: 'center' }}>Loading donor details from the cloud...</div>}{profile && donor && <>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20, paddingBottom: 16, borderBottom: '1px solid var(--border)' }}><div style={{ display: 'flex', gap: 16, flex: 1 }}><div className="member-avatar" style={{ width: 56, height: 56, fontSize: '1.3rem', flexShrink: 0 }}>{initials}</div><div><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><h2 style={{ margin: 0, color: 'var(--navy)', fontSize: '1.15rem' }}>{donor.name}</h2><button className="btn btn-ghost btn-sm" onClick={() => onEdit(donor)}><Edit2 size={15} /></button></div>{hebrewName && <div dir="rtl" style={{ fontSize: '1.05rem', fontWeight: 700, color: 'var(--navy-light)', background: 'var(--blue-bg)', borderRadius: 8, padding: '4px 10px', margin: '6px 0', display: 'inline-block' }}>{hebrewName}</div>}<div style={{ color: 'var(--text-muted)', fontSize: '0.82rem', display: 'flex', gap: 8, flexWrap: 'wrap' }}><span style={{ fontWeight: 800, color: 'var(--navy-light)', background: 'var(--blue-bg)', padding: '2px 8px', borderRadius: 4 }}>ID: {donor.displayId || donor.id}</span>{donor.phone && <span>{donor.phone}</span>}{donor.email && <span>· {donor.email}</span>}</div></div></div><div style={{ textAlign: 'right' }}><div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Open Balance</div><div style={{ fontSize: '1.4rem', fontWeight: 800, color: Number(summary.pledgeBalance||0)>0?'var(--red)':'var(--green)' }}>${money(summary.pledgeBalance)}</div></div></div>
      <div style={{ display: 'flex', gap: 10, marginBottom: 20 }}><button type="button" className="btn btn-primary" style={{ flex: 1, textAlign: 'center' }} onClick={() => { setShowPayment(true); setNotice(''); }}>💳 Process Payment</button><button type="button" className="btn btn-secondary" style={{ flex: 1, textAlign: 'center' }} onClick={() => { setShowRecurring(true); setNotice(''); }}>🔁 Set Up Recurring</button></div>
      <div style={{ display: 'flex', borderBottom: '1px solid var(--border)', marginBottom: 20, overflowX: 'auto' }}>{tabs.map(([key,label]) => <button key={key} onClick={() => setTab(key)} style={{ padding: '10px 12px', border: 'none', background: 'none', cursor: 'pointer', fontWeight: 700, fontSize: '0.78rem', color: tab === key ? 'var(--navy-light)' : 'var(--text-muted)', borderBottom: tab === key ? '3px solid var(--navy-light)' : '3px solid transparent', whiteSpace: 'nowrap' }}>{label}</button>)}</div>
      {tab === 'overview' && <div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 10, marginBottom: 20 }}>{[{label:'Total Given',value:`$${money(summary.approvedTotal)}`,color:'var(--green)'},{label:'Total Pledged',value:`$${money(summary.pledgedTotal)}`,color:'var(--gold)'},{label:'Active Recurring',value:String(summary.activeRecurringCount || 0),color:'var(--navy-light)'}].map(item => <div key={item.label} style={{ background: 'var(--bg-input)', borderRadius: 10, padding: 12, textAlign: 'center' }}><div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>{item.label}</div><div style={{ fontSize: '1.1rem', fontWeight: 800, color: item.color }}>{item.value}</div></div>)}</div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}><div style={{ background: 'var(--bg-input)', borderRadius: 12, padding: 14 }}><div style={{ fontWeight: 700, color: 'var(--navy)', borderBottom: '1px solid var(--border)', paddingBottom: 6, marginBottom: 10 }}>יידיש / Family Info</div>{[['Pre-Title',donor.preTitle],['Hebrew First',donor.hebFirstName],['Hebrew Last',donor.hebLastName],['Title',donor.title],['Post-Title',donor.postTitle],['His Father',donor.hisFather],['Her Father',donor.herFather]].map(([label,value]) => value ? <div key={label} style={{ display: 'flex', justifyContent: 'space-between', gap: 8, fontSize: '0.84rem', marginBottom: 7 }}><span style={{ color: 'var(--text-muted)' }}>{label}:</span><span dir="rtl" style={{ fontWeight: 600 }}>{value}</span></div> : null)}</div><div style={{ background: 'var(--bg-input)', borderRadius: 12, padding: 14 }}><div style={{ fontWeight: 700, color: 'var(--navy)', borderBottom: '1px solid var(--border)', paddingBottom: 6, marginBottom: 10 }}>Contact Details</div>{[['Main',donor.phone],['Home',donor.homePhone],['Mobile 1',donor.mobilePhone],['Mobile 2',donor.mobilePhone2],['Phone 3',donor.phone3],['Email',donor.email],['Address',donor.address],['City',donor.city],['Province',donor.province],['Postal',donor.postalCode]].map(([label,value]) => value ? <div key={label} style={{ display: 'flex', justifyContent: 'space-between', gap: 8, fontSize: '0.84rem', marginBottom: 7 }}><span style={{ color: 'var(--text-muted)' }}>{label}:</span><span style={{ textAlign: 'right' }}>{value}</span></div> : null)}</div></div></div>}
      {tab === 'transactions' && <RecordTable rows={profile.payments.filter(payment => payment.type !== 'declined')} columns={['Date','Amount','Method','Deposit','Status']} render={payment => [payment.date,`${payment.currency} $${money(payment.amount)}`,String(payment.method || '').replace('_',' '),payment.depositStatus || 'Direct',statusBadge(payment.type)]} empty="No payments found for this donor." onRow={payment => setSelectedPayment(payment)} />}
      {tab === 'pledges' && <><div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: 10, marginBottom: 16 }}>{[{label:'Total Pledges',value:summary.pledgedTotal},{label:'Approved Paid',value:summary.pledgePaidTotal},{label:'Pending',value:summary.pledgePendingTotal},{label:'Future Scheduled',value:summary.scheduledTotal},{label:'Unscheduled Balance',value:summary.pledgeBalance}].map(item => <div key={item.label} style={{ background: 'var(--bg-input)', borderRadius: 10, padding: 12, textAlign: 'center' }}><div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>{item.label}</div><div style={{ fontSize: '1.1rem', fontWeight: 800 }}>${money(item.value)}</div></div>)}</div><RecordTable rows={profile.pledges} columns={['Pledge Date','Pledge','Approved','Pending','Scheduled','Balance']} render={pledge => [pledge.date,`${pledge.currency || 'CAD'} $${money(pledge.amount)}`,`$${money(pledge.paid)}`,`$${money(pledge.pending)}`,`$${money(pledge.scheduled)}`,`$${money(pledge.balance)}`]} empty="No pledges found for this donor." onRow={pledge => setSelectedPledgeId(pledge.id)} /></>}
      {tab === 'recurring' && <RecordTable rows={profile.recurring} columns={['Next Date','Amount','Frequency','Method','Status']} render={schedule => [schedule.nextDate,`${schedule.currency} $${money(schedule.amount)}`,schedule.frequency,String(schedule.method || '').replace('_',' '),schedule.active ? 'Active' : 'Paused']} empty="No recurring payments found for this donor." onRow={schedule => setSelectedSchedule({ ...schedule, donorName: donor.name })} />}
      {tab === 'declined' && <RecordTable rows={declined} columns={['Date','Amount','Method','Notes','Status']} render={payment => [payment.date,`${payment.currency} $${money(payment.amount)}`,String(payment.method || '').replace('_',' '),payment.notes || '',statusBadge(payment.type)]} empty="No declined payments." onRow={payment => setSelectedPayment(payment)} />}
      {tab === 'notes' && <div><textarea value={notes} onChange={event => setNotes(event.target.value)} rows={8} style={{ width: '100%' }} /><button className="btn btn-primary" style={{ marginTop: 12 }} onClick={() => void saveNotes()} disabled={saving}>{saving ? 'Saving...' : 'Save Notes'}</button></div>}
      <div style={{ color: 'var(--text-muted)', fontSize: 12, marginTop: 16 }}>Each activity tab shows at most the latest 50 records so the page stays responsive.</div>
    </>}</div>
</div></div>{showPayment && donor && <div className="modal-overlay" onClick={() => setShowPayment(false)}><div onClick={event => event.stopPropagation()} style={{ width: 'min(900px,92vw)', maxHeight: '92vh', overflowY: 'auto' }}><OnlinePaymentForm donor={{ id: donor.id, name: donor.name, email: donor.email }} onCancel={() => setShowPayment(false)} onCreated={status => { setShowPayment(false); setNotice(status === 'pending' ? 'Check saved safely as pending.' : 'Payment saved safely.'); setTab('transactions'); void loadProfile(); }} /></div></div>}{showRecurring && donor && <div className="modal-overlay" onClick={() => setShowRecurring(false)}><div onClick={event => event.stopPropagation()} style={{ width: 'min(820px,92vw)', maxHeight: '92vh', overflowY: 'auto' }}><CloudRecurringPaymentForm donor={{ id: donor.id, name: donor.name }} onCancel={() => setShowRecurring(false)} onCreated={() => { setShowRecurring(false); setNotice('Recurring payment schedule saved safely.'); setTab('recurring'); void loadProfile(); }} /></div></div>}{selectedPayment && <CloudPaymentDetailsModal payment={{ ...selectedPayment, donorName: donor?.name }} onClose={() => setSelectedPayment(null)} onUpdated={payment => { setSelectedPayment(payment); void loadProfile(); }} />}{selectedPledgeId && <CloudPledgeDetailsModal pledgeId={selectedPledgeId} onClose={() => setSelectedPledgeId(null)} />}{selectedSchedule && <CloudScheduleDetailsModal schedule={selectedSchedule} onClose={() => setSelectedSchedule(null)} onUpdated={schedule => { setSelectedSchedule(schedule); setProfile(current => current ? { ...current, recurring: current.recurring.map(item => item.id === schedule.id ? schedule : item) } : current); }} />}</>;
};

const RecordTable: React.FC<{ rows: any[]; columns: string[]; render: (row: any) => React.ReactNode[]; empty: string; onRow?: (row: any) => void }> = ({ rows, columns, render, empty, onRow }) => <div className="table-container"><table><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => onRow?.(row)} style={onRow ? { cursor: 'pointer' } : undefined}>{render(row).map((value,index) => <td key={index}>{value}</td>)}</tr>)}{rows.length === 0 && <tr><td colSpan={columns.length} style={{ padding: 30, textAlign: 'center' }}>{empty}</td></tr>}</tbody></table></div>;
