import React, { useEffect, useRef, useState } from 'react';
import { Edit2, X } from 'lucide-react';

type Account = { id: string; name: string; type: string };
const money = (value: number) => Number(value || 0).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export const CloudBillDetailsModal: React.FC<{ bill: any; onClose: () => void; onMarkPaid?: (bill: any) => void; onUpdated?: (bill: any) => void }> = ({ bill: initialBill, onClose, onMarkPaid, onUpdated }) => {
  const [bill, setBill] = useState(initialBill); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [accounts, setAccounts] = useState<Account[]>([]);
  const [form, setForm] = useState({ vendor: initialBill.vendor || '', amount: String(initialBill.amount || ''), currency: initialBill.currency || 'CAD', exchangeRate: String(initialBill.exchangeRate || 1.35), dueDate: initialBill.dueDate || '', category: initialBill.category || '', status: initialBill.status || 'pending', sourceAccountId: initialBill.sourceAccountId || '', taxable: Boolean(initialBill.taxable), memo: initialBill.memo || '' });
  const requestId = useRef('');
  useEffect(() => { if (!editing || accounts.length) return; fetch('/api/v3/accounts?limit=100').then(response => response.json()).then(data => { if (data.success) setAccounts(data.items); }).catch(() => setError('Unable to load account choices.')); }, [editing, accounts.length]);
  const set = (field: string, value: string | boolean) => setForm(current => ({ ...current, [field]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setError(''); const amount = Number(form.amount); if (!form.vendor.trim() || !Number.isFinite(amount) || amount <= 0 || !form.dueDate || !form.category) { setError('Vendor, positive amount, date, and category are required.'); return; } setSaving(true); const key = requestId.current || crypto.randomUUID(); requestId.current = key; try { const data: any = { vendor: form.vendor.trim(), amount, currency: form.currency, dueDate: form.dueDate, category: form.category, status: form.status, taxable: form.taxable, memo: form.memo.trim() }; if (form.currency === 'USD') data.exchangeRate = Number(form.exchangeRate) || 1.35; if (form.sourceAccountId) data.sourceAccountId = form.sourceAccountId; const response = await fetch(`/api/v3/records/bills/${encodeURIComponent(bill.id)}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify({ revision: bill.revision, data }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || 'Unable to save bill changes.'); requestId.current = ''; const categoryName = accounts.find(account => account.id === result.item.category)?.name || bill.categoryName; const sourceName = accounts.find(account => account.id === result.item.sourceAccountId)?.name || bill.sourceName; const updated = { ...bill, ...result.item, categoryName, sourceName }; setBill(updated); setEditing(false); onUpdated?.(updated); } catch (reason: any) { requestId.current = ''; setError(reason.message || 'Unable to save bill changes.'); } finally { setSaving(false); } };
  return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={event => event.stopPropagation()} style={{ maxWidth: editing ? 760 : 680, width: '92%', maxHeight: '90vh', overflowY: 'auto' }}>
    <div className="modal-header"><div><h2 style={{ margin: 0 }}>{editing ? 'Edit Bill' : 'Bill Details'}</h2><div style={{ color: 'var(--text-muted)', marginTop: 4 }}>{bill.vendor}</div></div><button className="modal-close" onClick={onClose}><X size={20} /></button></div>
    {editing ? <form onSubmit={save}><div className="modal-body">{error && <div style={{ color: 'var(--red)', fontWeight: 700, marginBottom: 14 }}>{error}</div>}<div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 14 }}>
      <label className="form-group" style={{ margin: 0 }}><span>Vendor / Payee *</span><input value={form.vendor} onChange={event => set('vendor', event.target.value)} /></label><label className="form-group" style={{ margin: 0 }}><span>Amount *</span><input type="number" min="0.01" step="0.01" value={form.amount} onChange={event => set('amount', event.target.value)} /></label>
      <label className="form-group" style={{ margin: 0 }}><span>Currency</span><select value={form.currency} onChange={event => set('currency', event.target.value)}><option>CAD</option><option>USD</option></select></label>{form.currency === 'USD' && <label className="form-group" style={{ margin: 0 }}><span>Exchange Rate</span><input type="number" min="0.0001" step="0.0001" value={form.exchangeRate} onChange={event => set('exchangeRate', event.target.value)} /></label>}
      <label className="form-group" style={{ margin: 0 }}><span>Due Date *</span><input type="date" value={form.dueDate} onChange={event => set('dueDate', event.target.value)} /></label><label className="form-group" style={{ margin: 0 }}><span>Status</span><select value={form.status} disabled={bill.status === 'paid'} onChange={event => set('status', event.target.value)}><option value="pending">Pending</option><option value="urgent">Urgent</option>{bill.status === 'paid' && <option value="paid">Paid</option>}</select></label>
      <label className="form-group" style={{ margin: 0 }}><span>Expense Category *</span><select value={form.category} onChange={event => set('category', event.target.value)}><option value="">Select category</option>{accounts.filter(account => account.type === 'expense').map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="form-group" style={{ margin: 0 }}><span>Paid From</span><select value={form.sourceAccountId} disabled={bill.status !== 'paid'} onChange={event => set('sourceAccountId', event.target.value)}><option value="">Not paid</option>{accounts.filter(account => account.type === 'asset' || account.type === 'liability').map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label>
      <label className="form-group" style={{ margin: 0, gridColumn: '1 / -1' }}><span>Memo</span><textarea rows={4} maxLength={2000} value={form.memo} onChange={event => set('memo', event.target.value)} /></label><label style={{ display: 'flex', gap: 8, alignItems: 'center' }}><input type="checkbox" checked={form.taxable} onChange={event => set('taxable', event.target.checked)} /> Taxable</label>
    </div></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={() => { setEditing(false); setError(''); }}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving securely...' : 'Save All Changes'}</button></div></form> : <>
      <div className="modal-body">{error && <div style={{ color: 'var(--red)', fontWeight: 700, marginBottom: 14 }}>{error}</div>}<div style={{ textAlign: 'center', padding: '8px 0 22px', borderBottom: '1px solid var(--border)', marginBottom: 20 }}><div style={{ color: 'var(--text-muted)', fontSize: 12, textTransform: 'uppercase' }}>Bill Amount</div><div style={{ color: bill.status === 'paid' ? 'var(--green)' : 'var(--red)', fontSize: 30, fontWeight: 900 }}>{bill.currency || 'CAD'} ${money(bill.amount)}</div><span className={`badge ${bill.status === 'paid' ? 'badge-green' : bill.status === 'urgent' ? 'badge-red' : 'badge-yellow'}`} style={{ textTransform: 'capitalize' }}>{bill.status}</span></div>
      <section style={{ background: 'var(--bg-input)', borderRadius: 12, padding: 16, marginBottom: 16 }}><h3 style={{ margin: '0 0 12px', color: 'var(--navy)' }}>Expense Information</h3><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}><Detail label="Vendor / Payee" value={bill.vendor} /><Detail label="Due Date" value={bill.dueDate} /><Detail label="Paid Date" value={bill.paidDate || '—'} /><Detail label="Category" value={bill.categoryName || bill.category || 'Uncategorized'} /><Detail label="Paid From" value={bill.sourceName || bill.sourceAccountId || '—'} /><Detail label="Currency" value={bill.currency || 'CAD'} />{bill.currency === 'USD' && <Detail label="Exchange Rate" value={bill.exchangeRate || '—'} />}<Detail label="Taxable" value={bill.taxable ? 'Yes' : 'No'} /><Detail label="Payroll Expense" value={bill.isPayroll ? 'Yes' : 'No'} /><Detail label="T4A Eligible" value={bill.t4aEligible ? 'Yes' : 'No'} /></div></section>
      <section style={{ background: 'var(--bg-input)', borderRadius: 12, padding: 16 }}><h3 style={{ margin: '0 0 10px', color: 'var(--navy)' }}>Reference Information</h3><Detail label="Memo" value={bill.memo || '—'} /><div style={{ marginTop: 10 }}><Detail label="Bill ID" value={bill.id} /></div>{bill.bankTransactionId && <div style={{ marginTop: 10 }}><Detail label="Bank Transaction" value={bill.bankTransactionId} /></div>}{bill.projectId && <div style={{ marginTop: 10 }}><Detail label="Project" value={bill.projectId} /></div>}</section></div>
      <div className="modal-footer"><button className="btn btn-secondary" onClick={onClose}>Close</button><button className="btn btn-secondary" onClick={() => setEditing(true)}><Edit2 size={15} /> Edit All Details</button>{bill.status !== 'paid' && onMarkPaid && <button className="btn btn-primary" onClick={() => onMarkPaid(bill)}>Mark Paid</button>}</div>
    </>}
  </div></div>;
};

const Detail: React.FC<{ label: string; value: React.ReactNode }> = ({ label, value }) => <div><div style={{ color: 'var(--text-muted)', fontSize: 11, textTransform: 'uppercase', marginBottom: 3 }}>{label}</div><div style={{ fontWeight: 700, overflowWrap: 'anywhere' }}>{value}</div></div>;
